---
title: "tSNE_XRclassifier_3grps"
author: "Jingru Yu"
date: '2024-06-03'
output: html_document
---

# Load packages

```{r, message=FALSE, warning=FALSE}
#rm(list=ls())
options(scipen=999999999)
pathmeth <-"D:/Jingru/methylation"
pathref <- "D:/Jingru/references"
pathclass <- "D:/Jingru/classification"
pathdvdf <- "D:/Jingru/deconv/Data"

library(dplyr) 
library(openxlsx)
library(tidyverse)
library(reshape2)
library(data.table) #detDT,fread
library(ggplot2)
library(RSpectra)
library(Rtsne)
library(ggrepel)
library(ggpubr)
library(factoextra)

#do parallel
library(doParallel)  
library(foreach)
library(impute) #impute
library(rstatix) #comparison in plots

#create folder
createFolder <- function(pathtemp,nameFolder){
folder <- paste0(pathtemp, "/", nameFolder)

if (file.exists(folder)) {
 cat("The folder already exists")
} else {dir.create(folder)}
}

#function cbind.fill, combine cols with different lengths
cbind.fill <- function(...){
    nm <- list(...) 
    nm<-lapply(nm, as.matrix)
    n <- max(sapply(nm, nrow)) 
    do.call(cbind, lapply(nm, function (x) 
    rbind(x, matrix(, n-nrow(x), ncol(x))))) 
}

### function, to print the name of an object
print_name <- function(x) {
  print(deparse(substitute(x)))
} #works differently inside and outside of a function

## load R codes

source(file.path(pathmeth,"mnp_training-master/R","RSpectra_pca.R"))

pathmeth <- "D:/Jingru/methylation"
pathdvdf <- "D:/Jingru/deconv/Data"
pathref <- "D:/Jingru/references"

pathsampBF="D:/Jingru/deconv/Data/XR_BFs/BF_covFiles"
pathsampout="D:/Jingru/deconv/Output"
```

# t-SNE plots by pathological groups and sample types

```{r tSNE, message=FALSE, warning=FALSE}

samp_clin <- read.xlsx(file.path(pathdvdf,"Upload_processed",
                              "206samples_all_clin_clean.xlsx"),
                    sheet=1, skipEmptyRows=FALSE, colNames = TRUE)
    
load(file=file.path(pathdvdf,"Upload_processed/XRclassifier",
                    "24-07-02-TCGA_xr.anno_60k_LUAD.DLBC.CTRL.BRCA.GBM.Rdata"))

anno_train$Sample_tp.2cat <- ifelse(anno_train$Sample_tp.3cat=="FFPE","FFPE","BF")
anno_train$TCGA_Project_subgrp=
      ifelse(anno_train$TCGA_Project_subgrp=="MCF GBM","GBM",anno_train$TCGA_Project_subgrp)

load(file=file.path(pathdvdf,"Upload_processed/XRclassifier",
                    "LUAD.DLBC.CTRL.BRCA.GBM_CSF.FFPE_beta20k_impute_comb.RData"))
  or_index <- anno_train$TCGA_ID
  imp_df_filter_or <- imp_df_filter[or_index, ]

    ## Remove any NA
    betas_trans <- imp_df_filter_or[,!colSums(!is.finite(imp_df_filter_or))]
    
    rm(.Random.seed, envir=globalenv())  #remove seed

    pca <- prcomp_svds(betas_trans,k=20)
    #perplex_vec <- c(2,3,4,5,8,10,13,15)
    perplex_vec=4;i=1
    
    rm(.Random.seed, envir=globalenv())  #remove seed
    set.seed(91235)
    
    # calculate tSNE
    res <- Rtsne(pca$x, pca=FALSE, max_iter=2500,theta=0.0,verbose=T, perplexity=perplex_vec[i])

    meth_class <- as.factor(anno_train$TCGA_Project_subgrp)
    levels(meth_class) #3
    # shape_class <- factor(anno_train$Sample_tp.2cat, order=T,
    #                       levels=c("BF","FFPE"), labels=c("BF","FFPE"))
    # levels(shape_class)
    
    tsne_plot.df <- 
        data.frame(x = res$Y[,1], y = res$Y[,2],
                   cluster = factor(meth_class, labels=as.vector(levels(meth_class))),
                   #shape.f = factor(shape_class, labels=as.vector(levels(shape_class))),
                   Sentrix_ID = rownames(pca$x))
      
      #save plot data
      # write.csv(tsne_plot.df, file=file.path("D:/Jingru/deconv/Output/Output_BFs",
      #   paste0("P",perplex_vec[i],"-LUAD.DLBC.CTRL_XR_Tsne_iter2500.csv")),row.names = FALSE)
      
      #different color pattern        
      meth3 <- factor(tsne_plot.df$cluster, order=T,
                      levels=c("DLBC","LUAD","BRCA","GBM","CTRL (HighT)", "CTRL (N)"))
      hc.norm = hclust(dist(tsne_plot.df[,c(1,2)]))
      tsne_plot.df$hclust = meth3
      hc.norm.cent = tsne_plot.df %>% group_by(hclust) %>% dplyr::select(x, y) %>% 
        summarise(x=median(x), y=median(y))
      
      col_code <- c("DLBC"="#e4703a","LUAD"="#b890e0","BRCA"="#6e1e33",
                    "GBM"="#006ead", "CTRL (HighT)"="#77DD77", "CTRL (N)"="#228b22")
      
      print(labeled_tsne <-
              ggplot(data=tsne_plot.df, aes(x=x, y=y, color = hclust, label=TRUE))+
              xlab("t-SNE 1") + ylab("t-SNE 2") +
              #geom_point(aes(shape=shape.f)) + 
              #scale_shape_manual(values=c(19,17)) + 
              geom_point()+
              scale_x_continuous(breaks=seq(-120, 120, by = 40),
                     labels=seq(-120, 120, by = 40), limits=c(-125, 125), expand = c(0, 0)) +
              scale_y_continuous(breaks=seq(-120, 120, by = 40),
                     labels=seq(-120, 120, by = 40), limits=c(-125,125), expand = c(0, 0)) + 
              theme_bw() +
              geom_label_repel(aes(label = hclust), data=hc.norm.cent, 
                               label.size = 0.015, max.overlaps = Inf) + 
              scale_colour_manual(values = col_code, labels=meth3) +
              theme(panel.grid.major = element_blank(), 
                    panel.grid.minor = element_blank(),
                    panel.background = element_rect(colour = "black", fill=NA),
                    legend.position="none"))
    
#color by shapes
#######################################
    rm(.Random.seed, envir=globalenv())  #remove seed
    set.seed(91235)
    
    # calculate tSNE
    res <- Rtsne(pca$x, pca=FALSE, max_iter=2500,theta=0.0,verbose=T, perplexity=4)

    # meth_class <- as.factor(anno_train$TCGA_Project_subgrp)
    # levels(meth_class) #3
    meth_class <- factor(anno_train$Sample_tp.2cat, order=T,
                          levels=c("BF","FFPE"), labels=c("BF","FFPE"))
    levels(meth_class)
    
    tsne_plot.df <- 
        data.frame(x = res$Y[,1], y = res$Y[,2],
                   cluster = factor(meth_class, labels=as.vector(levels(meth_class))),
                   #shape.f = factor(shape_class, labels=as.vector(levels(shape_class))),
                   Sentrix_ID = rownames(pca$x))
      
      #save plot data
      # write.csv(tsne_plot.df, file=file.path("D:/Jingru/deconv/Output/Output_BFs",
      #   paste0("P4","-SampleTypes_XR_Tsne.csv")),row.names = FALSE)
      
      meth3 <- factor(tsne_plot.df$cluster, order=T,
                       levels=c("BF","FFPE"))
      hc.norm = hclust(dist(tsne_plot.df[,c(1,2)]))
      tsne_plot.df$hclust = meth3
      hc.norm.cent = tsne_plot.df %>% group_by(hclust) %>% dplyr::select(x, y) %>% 
        summarise(x=median(x), y=median(y))

      col_code <- c("BF"="#FC766AFF","FFPE"="#5B84B1FF")
      
      print(labeled_tsne <-
              ggplot(data=tsne_plot.df, aes(x=x, y=y, color = hclust, label=F))+
              labs(x="t-SNE 1", y="t-SNE 2")+
              geom_point() + 
              #scale_shape_manual(values=c(19,17)) + 
              scale_x_continuous(breaks=seq(-120, 120, by = 40),
                     labels=seq(-120, 120, by = 40), limits=c(-125,125), expand = c(0, 0)) +
              scale_y_continuous(breaks=seq(-120, 120, by = 40),
                     labels=seq(-120, 120, by = 40), limits=c(-125,125), expand = c(0, 0)) + 
              theme_bw() +
              scale_colour_manual(values = col_code) +
              theme(panel.grid.major = element_blank(), 
                    panel.grid.minor = element_blank(),
                    panel.background = element_rect(colour = "black", fill=NA),
                    legend.position.inside = c(0.8,0.8)))
      
```

# Classifier score, XR vs. array

```{r score, XR vs. array}
################################    
#make plots with average data

test_m <- read.xlsx(file.path(pathdvdf,"Upload_processed/XRclassifier",
          "24-07-02-score.comp_XRclassifierVS.array_18samples.xlsx"),
                       sheet=1, skipEmptyRows=FALSE, colNames = TRUE)
test_m2 <- test_m %>% 
mutate(temp1=sapply(str_split(TCGA_ID, "X",  n = 2), `[`, 1),
    temp2=ifelse(str_sub(temp1,-1,-1)=="v", as.numeric(gsub("\\D", "", temp1)),
                 substring(temp1, 3)),
    BF_id=paste0(substr(TCGA_ID,1,2),temp2),
    can_grp=ifelse(TCGA_ID %in% c("BF1059XR2324", "BF3241XR21B",  "BF168XR23A",
             "BF3041XR23B",  "BF3077XR2324", "BF3122XR23B"), "Controls","Tumors"))

mean(test_m2[test_m2$Classifier=="XR","mean_score"])
sd(test_m2[test_m2$Classifier=="XR","mean_score"])

# Compute the analysis of variance

pwc2 <- test_m2[test_m2$can_grp!="Controls",] %>% 
  wilcox_test(mean_score ~ Classifier, paired = TRUE)
pwc2 #0.0122

my_comparisons <- list(c("TCGA/CNS", "XR"))

pp1 <- 
  ggplot(data=test_m2[test_m2$can_grp!="Controls",], aes(x = Classifier, y = mean_score)) + 
  geom_hline(yintercept = 0.2, linetype=1, color = "gray80", linewidth=0.5) +
  geom_hline(yintercept = 0.4, linetype=1, color = "gray80", linewidth=0.5) +
  geom_hline(yintercept = 0.6, linetype=1, color = "gray80", linewidth=0.5) +
  geom_hline(yintercept = 0.8, linetype=1, color = "gray80", linewidth=0.5) +
  geom_boxplot(aes(fill = Classifier), alpha = .2) +
  geom_line(aes(group = BF_id),color="gray70",linewidth=0.8) + 
  geom_point(size = 2)   + 
  scale_y_continuous(breaks=seq(0, 1, by = 0.2),
                     labels=seq(0, 1, by = 0.2), limits=c(0,1.02), expand = c(0, 0)) + 
  labs(y="Classifier score")+
  theme(panel.background = element_blank(),
        # panel.grid.major.y = element_line(color = "grey80",
        #                                   linetype = 1),
        panel.border = element_rect(color="black",fill=NA),
        text=element_text(size=14, face="bold"),
        axis.text.x = element_text(size=14,face="bold"),
        axis.text.y = element_text(size=14, face="bold"),
        axis.title=element_text(size=13,face="bold"),
        legend.position="none",
        legend.title=element_blank()) +
  guides(fill=guide_legend(ncol=1,byrows=T)) +
  stat_compare_means(comparisons = my_comparisons,
                     method = "wilcox.test",paired = TRUE)+ 
  # Add pairwise comparisons p-value
  stat_compare_means(label.y = 0.2) 

pp2 <- 
  ggplot(data=test_m2[test_m2$can_grp=="Controls",], aes(x = Classifier, y = mean_score)) + 
  geom_hline(yintercept = 0.2, linetype=1, color = "gray80", linewidth=0.5) +
  geom_hline(yintercept = 0.4, linetype=1, color = "gray80", linewidth=0.5) +
  geom_hline(yintercept = 0.6, linetype=1, color = "gray80", linewidth=0.5) +
  geom_hline(yintercept = 0.8, linetype=1, color = "gray80", linewidth=0.5) +
  geom_boxplot(aes(fill = Classifier), alpha = .2) +
  geom_line(aes(group = BF_id),color="gray70",linewidth=0.8) + 
  geom_point(size = 2)   + 
  scale_y_continuous(breaks=seq(0, 1, by = 0.2),
                     labels=seq(0, 1, by = 0.2), limits=c(0,1.02), expand = c(0, 0)) + 
  labs(y="Classifier score")+
  theme(panel.background = element_blank(),
        # panel.grid.major.y = element_line(color = "grey80",
        #                                   linetype = 1),
        panel.border = element_rect(color="black",fill=NA),
        text=element_text(size=14, face="bold"),
        axis.text.x = element_text(size=14,face="bold"),
        axis.text.y = element_text(size=14, face="bold"),
        axis.title=element_text(size=13,face="bold"),
        legend.position="none",
        legend.title=element_blank()) +
  guides(fill=guide_legend(ncol=1,byrows=T)) +
  stat_compare_means(comparisons = my_comparisons,method = "wilcox.test",paired = TRUE)+ 
  # Add pairwise comparisons p-value
  stat_compare_means(label.y = 0.2) 


pp_m <- ggarrange(pp1,pp2, ncol = 2, nrow = 1, 
                    common.legend = F, legend= NULL,  widths = c(1.4, 1.4))
pp_m

```
 