---
title: "chk_correlation"
author: "Jingru Yu"
date: '2024-07-01'
output: html_document

---

# Load packages and paths

```{r setup, include=FALSE}
#rm(list=ls())

library(dplyr)
library(ggplot2)
library(tidyverse)
library(stringr)
library(openxlsx)
library(data.table) #detDT
library(scales)

library(ggpubr) #ggarrange
library(minfi)
library(RColorBrewer)

### function cbind.fill, combine cols with different lengths
cbind.fill<-function(...){
    nm <- list(...) 
    nm<-lapply(nm, as.matrix)
    n <- max(sapply(nm, nrow)) 
    do.call(cbind, lapply(nm, function (x) 
    rbind(x, matrix(, n-nrow(x), ncol(x))))) 
}

pathref <- "D:/Jingru/references"
pathpro <-"D:/Jingru/deconv/Data/Upload_processed" 
```

# Load WGBS/RRBS/XRBS/EPIC of K562

```{r PublicK562}

#WGBS
k562_wgbs <- fread(file.path(pathref,"RefData/K562_WGBS/cut15bp",
  "WGBS_SRR4235743-merged.cov.SNPfiltered_clean.txt"),quote="",sep="\t")
colnames(k562_wgbs) <- c("chr","start","end","meth.cnt","depth")

k562_wgbs_2 <- as.data.frame(k562_wgbs) %>% filter(depth>=15) %>%
      mutate(beta=round(meth.cnt/depth,digits=5),
             chr_cpg_loc = paste0(chr,"_",start,"_",end))  

# RRBS
k562_rrbs <- fread(file.path(pathref,"RefData/K562_RRBS/ENCFF000MHC-hg38_SE",
  "ENCFF000MHC-merged.cov.SNPfiltered_clean.txt"),quote="",sep="\t")
colnames(k562_rrbs) <- c("chr","start","end","meth.cnt","depth")

k562_rrbs_2 <- as.data.frame(k562_rrbs) %>% filter(depth>=15) %>%
      mutate(beta=round(meth.cnt/depth,digits=5),
             chr_cpg_loc = paste0(chr,"_",start,"_",end)) 

k562_rrbscomb <- fread(file.path(pathref,"RefData/K562_RRBS/K562rrbs_comb2011-hg38_SE",
  "K562rrbs_comb2011-merged.cov.SNPfiltered_clean.txt"),quote="",sep="\t")
colnames(k562_rrbscomb) <- c("chr","start","end","meth.cnt","depth")

k562_rrbs_3 <- as.data.frame(k562_rrbscomb) %>% filter(depth>=15) %>%
      mutate(beta=round(meth.cnt/depth,digits=5),
             chr_cpg_loc = paste0(chr,"_",start,"_",end)) 


#0-based data, with CpGs from top and bottom strand as an entity
k562_rrbs <- read.table(file.path(pathref,"RefData/K562_RRBS","allCpG_rrbs_k562_sum2-5cov.bed"),
                     quote="",sep="\t")
colnames(k562_rrbs) <- c("chr","start","end","meth.cnt","depth")

k562_rrbs2_chr <- k562_rrbs %>%
      mutate(beta=round(meth.cnt/depth,digits=5),
             chr_cpg_loc = paste0(chr,"_",start,"_",end)) %>% filter(depth>=15)

# XRBS
#0-based data, with CpGs from top and bottom strand as an entity
k562_xrbs <- read.table(file.path(pathref,"RefData/K562_XRBS/GSE149954_RAW",
                                  "allCpG_xrbs_k562_sum2-5cov.bed"),
                     quote="",sep="\t")
colnames(k562_xrbs) <- c("chr","start","end","meth.cnt","depth")

k562_xrbs2_chr <- k562_xrbs %>%
      mutate(beta=round(meth.cnt/depth,digits=5),
             chr_cpg_loc = paste0(chr,"_",start,"_",end)) %>% filter(depth>=15)

# EPIC
# from R script "13EPIC_for_correlation.Rmd"
load(file=file.path(pathref,"RefData/K562_EPIC", "k562_epic_hg38.RData")) #k562_hg38_betas

#0-based data, with CpGs from top and bottom strand as an entity
k562_epic1 <- k562_hg38_betas[,c(2,3,4,5)]
colnames(k562_epic1)[4] <- "beta"

k562_epic1_chr <- k562_epic1 %>%
       mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end))

```

# Load array data

```{r arrayData}
load(file.path(pathpro,"large_data","array_samp.K562.3FFPE_beta.RData"))
#test_betas$CG <- rownames(test_betas)
# temp1 <- as.data.frame(test_betas[,c("CG","207831650102_R01C01","207831650102_R02C01",
#                             "207831650102_R03C01")])
                         
array_k562.100ng <- as.data.frame(array_samp_beta[,c("CG","207831650102_R01C01")])
array_k562.250ng <- as.data.frame(array_samp_beta[,c("CG","207831650102_R02C01")])

epicv2 <- as.data.frame(fread(file.path(pathpro,"large_data",
  "array.900k_hg38_chrXYM.SNP.filtered.bed")), header = F, sep="\t",stringsAsFactors=FALSE)
colnames(epicv2) <- c("chr","start","end","CG")

array_k562.100ng_1 <- merge(array_k562.100ng, epicv2, by="CG")
array_k562.100ng_1 <- array_k562.100ng_1 %>%
  mutate(chr_loc = paste0(chr,"_",start,"_",end))
array_k562.100ng_1 <- array_k562.100ng_1[,c(6,2)]
colnames(array_k562.100ng_1) <- c("chr_cpg_loc","beta")


array_k562.250ng_1 <- merge(array_k562.250ng, epicv2, by="CG")
array_k562.250ng_1 <- array_k562.250ng_1 %>%
  mutate(chr_loc = paste0(chr,"_",start,"_",end))
array_k562.250ng_1 <- array_k562.250ng_1[,c(6,2)]
colnames(array_k562.250ng_1) <- c("chr_cpg_loc","beta")


array_TF211 <- as.data.frame(array_samp_beta[,c("CG","207831650102_R03C01")])

array_TF211_1 <- merge(array_TF211, epicv2, by="CG")
array_TF211_1 <- array_TF211_1 %>%
  mutate(chr_loc = paste0(chr,"_",start,"_",end))
array_TF211_1 <- array_TF211_1[,c(6,2)]
colnames(array_TF211_1) <- c("chr_cpg_loc","beta")

#load TF samples
#load(file.path(pathclass,"Data/23-0814_UChicagoArray/processed/TF_betas.RData"))
# colnames(betas_CGcolumn)
# temp2 <- as.data.frame(betas_CGcolumn[,c("CG","207680760164_R05C01",
#                                          "207680760164_R07C01")])
# 
# array_samp_beta <- merge(temp1,temp2,by="CG",all.x=T,all.y=T)
# save(array_samp_beta,file=
#        file.path(pathpro,"large_data","array_samp.K562.3FFPE_beta.RData"))

array_TF640 <- as.data.frame(array_samp_beta[,c("CG","207680760164_R05C01")])

array_TF640_1 <- merge(array_TF640, epicv2, by="CG")
array_TF640_1 <- array_TF640_1 %>%
  mutate(chr_loc = paste0(chr,"_",start,"_",end))
array_TF640_1 <- array_TF640_1[,c(6,2)]
colnames(array_TF640_1) <- c("chr_cpg_loc","beta")

array_TF642 <- as.data.frame(array_samp_beta[,c("CG","207680760164_R07C01")])

array_TF642_1 <- merge(array_TF642, epicv2, by="CG")
array_TF642_1 <- array_TF642_1 %>%
  mutate(chr_loc = paste0(chr,"_",start,"_",end))
array_TF642_1 <- array_TF642_1[,c(6,2)]
colnames(array_TF642_1) <- c("chr_cpg_loc","beta")

```

# Load 3 TF sequenced data

```{r}

f="TF211s2XR2122_comb"
TF211_1 <- fread(file.path(pathpro,"methylation_call_FFPE",
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(TF211_1) <- c("chr","start","end","meth.cnt","depth")

TF211_2 <- as.data.frame(TF211_1) %>% filter(depth>=15) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))

f="TF640XR2122_comb"
TF640_1 <- fread(file.path(pathpro,"methylation_call_FFPE",
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(TF640_1) <- c("chr","start","end","meth.cnt","depth")

TF640_2 <- as.data.frame(TF640_1) %>% filter(depth>=15) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))

f="TF642XR2122_comb"
TF642_1 <- fread(file.path(pathpro,"methylation_call_FFPE",
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(TF642_1) <- c("chr","start","end","meth.cnt","depth")

TF642_2 <- as.data.frame(TF642_1) %>% filter(depth>=15) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))
```

# Load K562 data from different methods

```{r}

f="K56210ngrep1_comb" #"K56210ngXR21A_comb"
rep1_1 <- fread(file.path(pathpro,"methylation_call_benchmarks",
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(rep1_1) <- c("chr","start","end","meth.cnt","depth")

rep1_2 <- as.data.frame(rep1_1) %>% filter(depth>=15) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))

rep1_10cov <- as.data.frame(rep1_1) %>% filter(depth>=10) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))

f="K56210ngrep2_comb" #"K56210U10w1w2XR22A_comb"
rep2_1 <- fread(file.path(pathpro,"methylation_call_benchmarks",
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(rep2_1) <- c("chr","start","end","meth.cnt","depth")

rep2_2 <- as.data.frame(rep2_1) %>% filter(depth>=15) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))

rep2_10cov <- as.data.frame(rep2_1) %>% filter(depth>=10) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))

f="K56210ngrep12_comb"
rep12_1 <- fread(file.path(pathpro,"methylation_call_benchmarks",
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(rep12_1) <- c("chr","start","end","meth.cnt","depth")

rep12_2 <- as.data.frame(rep12_1) %>% filter(depth>=15) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))

rep12_comb <- merge(rep2_10cov, rep1_10cov, by="chr_cpg_loc",all.x=TRUE,all.y=TRUE)
rep12_comb[is.na(rep12_comb)] <- 0
rep12_comb1 <- rep12_comb %>%
  mutate(meth.cnt=meth.cnt.x+meth.cnt.y,
         depth=depth.x+depth.y,
         beta=round(meth.cnt/depth, digits=5))

rep12.10cov_comb.15cov <- as.data.frame(rep12_comb1) %>% 
  filter(depth>=15) %>%
  select( "meth.cnt","depth","chr_cpg_loc","beta")

rep12.10cov_comb.15cov_clean <- rep12_comb1[,c(1,14,15)] %>% 
  filter(depth>=15) %>%
  mutate(chr=sapply(str_split(chr_cpg_loc, "_",  n = 3), `[`, 1),
         start=as.numeric(sapply(str_split(chr_cpg_loc, "_",  n = 3), `[`, 2)),
         end=as.numeric(sapply(str_split(chr_cpg_loc, "_",  n = 3), `[`, 3))) %>%
  select(chr,start,end,meth.cnt,depth)

#Rscript "GetIntersectCG_fixList.R"
#load intersected K56210ngXR21A
load(file.path(pathpro,"large_data",
"K56210ngXR21A_comb-interblocks_allvars.RData"))

int_allcpg_15cov <- beta_maxcov_filter[!is.na(beta_maxcov_filter$beta),c(1,2,3,13,10,8,9)] %>%
  mutate(beta=round(beta,5)) %>%
  filter(total.x>=15)
int_allcpg_15cov <- int_allcpg_15cov[,1:5]

```

# Make heatmaps, array vs. enriched seq

```{r array vs. enriched seq}
source(file.path(pathpro,"R_fixed","correlation_plot2_clean.R"))

# correlation between enriched seq and microarray for the FFPE TF's, 
# Array vs. wgbs, array vs. enriched seq

TF640_co <- CorrelatePlot2(samp1=TF640_2, samp2=array_TF640_1, 
  assay_xr="FLEXseq, TF640", assay="EPICv2, TF640", covnum=15)
TF640_co2 <- TF640_co + ggtitle("Pearson's r=0.95")+
  theme(plot.title = element_text(hjust = 0.5))
#       rho       cor 
# 0.9012830 0.9470009 

TF642_co <- CorrelatePlot2(samp1=TF642_2, samp2=array_TF642_1, 
  assay_xr="FLEXseq, TF642", assay="EPICv2, TF642", covnum=15)
TF642_co2 <- TF642_co + ggtitle("Pearson's r=0.93")+
  theme(plot.title = element_text(hjust = 0.5))
#       rho       cor 
# 0.8883038 0.9250923 

TF211_co <- CorrelatePlot2(samp1=TF211_2, samp2=array_TF211_1, 
  assay_xr="FLEXseq, TF211", assay="EPICv2, TF211", covnum=15)
TF211_co2 <- TF211_co + ggtitle("Pearson's r=0.94")+
  theme(plot.title = element_text(hjust = 0.5))
#       rho       cor 
# 0.8727351 0.9389451
K562_xr_epic <- CorrelatePlot2(samp1=rep12.10cov_comb.15cov, samp2=k562_epic1_chr, 
  assay_xr='FLEXseq, rep1&2(v2)', assay="EPIC", covnum=15)
K562_xr_epic2 <- K562_xr_epic + ggtitle("Pearson's r = 0.96")+
  theme(plot.title = element_text(hjust = 0.5))
#0.8426689 0.9622628(use)

pm_TFcorr <- ggarrange(K562_xr_epic2, TF211_co2,TF640_co2,TF642_co2,
                 common.legend = TRUE, legend= "bottom",
                 ncol =2, nrow =2)
pm_TFcorr

# dev.new()  
# pdf(file=file.path(pathref,"Output/correlation", 
#                    paste0(str_sub(Sys.Date(), start = 3), "-4TFs_correlation.pdf")),  
#     width = 10, height = 3.35, useDingbats = FALSE)
# p.TFcorr
# dev.off() 
```

# K562 input titrations of array data

```{r}
K562_array100 <- CorrelatePlot2(samp1=array_k562.100ng_1, samp2=k562_epic1_chr, 
  assay_xr="EPICv2, input 100ng", assay="EPIC public", covnum=15)
K562_array100_2 <- K562_array100 + ggtitle("Pearson's r = 0.40")+
  theme(plot.title = element_text(hjust = 0.5))
suppressWarnings({K562_array100_2})
#       rho       cor 
# 0.4566024 0.3963214 

K562_array250 <- CorrelatePlot2(samp1=array_k562.250ng_1, samp2=k562_epic1_chr, 
  assay_xr="EPICv2, input 250ng", assay="EPIC public", covnum=15)
K562_array250_2 <- K562_array250 + ggtitle("Pearson's r = 0.68")+
  theme(plot.title = element_text(hjust = 0.5))
K562_array250_2
#       rho       cor 
# 0.6742229 0.6795308 

K562_array <- CorrelatePlot2(samp1=array_k562.100ng_1, samp2=array_k562.250ng_1, 
  assay_xr="EPICv2, input 100ng", assay="EPICv2, input 250ng", covnum=15)
K562_array_2 <- K562_array + ggtitle("Pearson's r = 0.82")+
  theme(plot.title = element_text(hjust = 0.5))
K562_array_2
#       rho       cor 
# 0.7983168 0.8169722 

```

# Density plot of Array vs. enriched seq

```{r density}
DrawDensityCompare <- function(array_df, xr_df, f){
array_m1 <- list(array_df[,c("chr_cpg_loc","beta")],
                 xr_df[,c("chr_cpg_loc","beta")])
array_m2 <- array_m1 %>% purrr::reduce(left_join, by="chr_cpg_loc")
colnames(array_m2) <- c("chr_cpg_loc","EPICv2","FLEXseq")
array_m2 <- array_m2[complete.cases(array_m2),]

#wide to long
array_m.long <- melt(setDT(as.data.frame(array_m2)),id.vars = 1, 
                 measure.vars = 2:length(colnames(array_m2)), variable.name = "Method")

p_v2 <- ggplot(array_m.long, aes(x=value,fill=Method)) + 
  geom_density(alpha=0.5, adjust = 1)+ 
  scale_y_continuous(breaks=seq(0, 5, by = 1),
                     labels=seq(0, 5, by = 1), limits=c(0,6)) + 
  labs(x="Beta value",y="Frequency")+
  scale_fill_manual(values = c("salmon2","#79b3b8")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(color="black",fill=NA),
        text=element_text(size=13,face = "bold"),
        strip.text.x = element_text(size = 13),
        strip.background = element_blank(),
        legend.position="bottom")

pm_v2 <- p_v2 + ggtitle(f)+
  theme(plot.title = element_text(hjust = 0.5))

return(pm_v2)
}

p.k562 <- DrawDensityCompare(array_df=k562_epic1_chr, xr_df=rep12.10cov_comb.15cov, f="K562")
p.TF211 <- DrawDensityCompare(array_df=array_TF211_1, xr_df=TF211_2, f="TF211")
p.TF640 <- DrawDensityCompare(array_df=array_TF640_1, xr_df=TF640_2, f="TF640")
p.TF642 <- DrawDensityCompare(array_df=array_TF642_1, xr_df=TF642_2, f="TF642")

pm_density <- ggarrange(p.k562,p.TF211,p.TF640,p.TF642,
                 common.legend = T, legend= "bottom",
                 ncol = 2, nrow = 2)
pm_density

# dev.new()  
# pdf(file=file.path(pathref,"Output/correlation", 
#                    paste0(str_sub(Sys.Date(), start = 3), "-4TFs_DensityPlot.pdf")),  
#     width = 8, height = 3, useDingbats = FALSE)
# p.density
# dev.off() 


```

# K562 input titrations of FLEXseq

```{r}

f="K5621ngU1020XR22A_comb"
k562.1ng_1 <- fread(file.path(pathpro,"methylation_call_benchmarks",
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(k562.1ng_1) <- c("chr","start","end","meth.cnt","depth")

k562.1ng_2 <- as.data.frame(k562.1ng_1) %>% filter(depth>=15) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))

f="K56210ngrep1_comb"
rep10ng_1 <- fread(file.path(pathpro,"methylation_call_benchmarks",
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(rep10ng_1) <- c("chr","start","end","meth.cnt","depth")

rep10ng_2 <- as.data.frame(rep10ng_1) %>% filter(depth>=15) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))

f="K562100ngXR23A_comb"
k562.100ng_1 <- fread(file.path(pathpro,"methylation_call_benchmarks",
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(k562.100ng_1) <- c("chr","start","end","meth.cnt","depth")

k562.100ng_2 <- as.data.frame(k562.100ng_1) %>% filter(depth>=15) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))


p10ngvs1ng_15cov <- CorrelatePlot2(samp1=rep10ng_2, samp2=k562.1ng_2, 
  assay_xr="Input 10ng", assay="Input 1ng", covnum=15)
p10ngvs1ng_15cov2 <- p10ngvs1ng_15cov + ggtitle("Pearson's r = 0.98")+
  theme(plot.title = element_text(hjust = 0.5))
#0.8781202 0.9755608

p10ngvs100ng_15cov <- CorrelatePlot2(samp1=rep10ng_2, samp2=k562.100ng_2, 
  assay_xr="Input 10ng", assay="Input 100ng", covnum=15)
#0.8913469 0.9767191
p10ngvs100ng_15cov2 <- p10ngvs100ng_15cov + ggtitle("Pearson's r = 0.98")+
  theme(plot.title = element_text(hjust = 0.5))

pm2 <- ggarrange(p10ngvs1ng_15cov2,p10ngvs100ng_15cov2,
                 common.legend = TRUE, legend= "bottom",
                 nrow = 1)
pm2

```




```{r}
source(file.path(pathpro,"R_fixed","correlation_plot2_clean.R"))

##########################################
#rep1 vs. rep2.

K562rep <- CorrelatePlot2(samp1=rep1_2, samp2=rep2_2, 
  assay_xr="FLEXseq, rep1", assay="FLEXseq, rep2", covnum=15)
K562rep_2 <- K562rep + ggtitle("Pearson's r = 0.98")+
  theme(plot.title = element_text(hjust = 0.5))
K562rep_2
#0.8904127 0.9781759(use)

##########################################
#WGBS vs. FLEXseq
#FLEXseq vs. EPIC

K562_wgbs2 <- CorrelatePlot2(samp1=k562_wgbs_2, samp2=rep12.10cov_comb.15cov, 
  assay_xr='WGBS', assay='FLEXseq, rep1&2', covnum=15)
K562_wgbs2_2 <- K562_wgbs2 + ggtitle("Pearson's r = 0.97")+
  theme(plot.title = element_text(hjust = 0.5))
K562_wgbs2_2
#0.8793548 0.9674620(use)

K562_xr_epic <- CorrelatePlot2(samp1=k562_epic1_chr, samp2=rep12.10cov_comb.15cov, 
  assay_xr='EPIC', assay='FLEXseq, rep1&2', covnum=15)
K562_xr_epic2 <- K562_xr_epic + ggtitle("Pearson's r = 0.96")+
  theme(plot.title = element_text(hjust = 0.5))
#0.8426689 0.9622628(use)
K562_xr_epic2

pm1 <- ggarrange(K562rep_2,K562_wgbs2_2,K562_xr_epic2,
                 common.legend = TRUE, legend= "bottom",
                 nrow = 1)
pm1

##########################################
#intersection
k562interBlock_15cov <- CorrelatePlot2(samp1=rep1_2, samp2=int_allcpg_15cov,
                           assay_xr="FLEXseq (original)", 
                           assay="FLEXseq (intersected)", covnum=15) 
k562interBlock_15cov_2 <- k562interBlock_15cov + ggtitle("Pearson's r = 0.96")+
  theme(plot.title = element_text(hjust = 0.5))
#0.9216491 0.9639445 #cov=15
#0.9197067 0.9581556 #cov=10

k562inter_epic2 <- CorrelatePlot2(samp1=int_allcpg_15cov, samp2=k562_epic1_chr,
                           assay_xr="FLEXseq (intersected)", assay="EPIC", covnum=15) 
k562inter_epic2_2 <- k562inter_epic2 + ggtitle("Pearson's r = 0.92")+
  theme(plot.title = element_text(hjust = 0.5))
#0.8114470 0.9173817

pm_k562interBlock <- ggarrange(k562interBlock_15cov_2, k562inter_epic2_2,
                 common.legend = TRUE, legend= "bottom",
                 nrow = 1)
pm_k562interBlock

##########################################
#Supplementary
wgbs_epic <- CorrelatePlot2(samp1=k562_wgbs_2, samp2=k562_epic1_chr,
                           assay_xr="WGBS", assay="EPIC", covnum=15)
wgbs_epic_2 <- wgbs_epic + ggtitle("Pearson's r = 0.97")+
  theme(plot.title = element_text(hjust = 0.5))
# 0.8815257 0.9698487

# wgbs_rrbs <- CorrelatePlot2(samp1=k562_wgbs_2, samp2=k562_rrbs2_chr, 
#                            assay_xr="WGBS", assay="RRBS", covnum=15)
# wgbs_rrbs_2 <- wgbs_rrbs + ggtitle("Pearson's r = 0.97")+
#   theme(plot.title = element_text(hjust = 0.5))
# 0.8764482 0.9664102

wgbs_rrbsv2 <- CorrelatePlot2(samp1=k562_wgbs_2, samp2=k562_rrbs_2, 
                           assay_xr="WGBS", assay="RRBS", covnum=15)
wgbs_rrbsv2_2 <- wgbs_rrbsv2 + ggtitle("Pearson's r = 0.97")+
  theme(plot.title = element_text(hjust = 0.5))
#0.8590027 0.9679179

wgbs_xrbs <- CorrelatePlot2(samp1=k562_wgbs_2, samp2=k562_xrbs2_chr, 
                           assay_xr="WGBS", assay="XRBS", covnum=15)
wgbs_xrbs_2 <- wgbs_xrbs + ggtitle("Pearson's r = 0.91")+
  theme(plot.title = element_text(hjust = 0.5))
# 0.7778747 0.9085829 

xr_epic <- CorrelatePlot2(samp1=rep12.10cov_comb.15cov, samp2=k562_epic1_chr,
                           assay_xr="FLEXseq, rep1&2", assay="EPIC", covnum=15)
xr_epic_2 <- xr_epic + ggtitle("Pearson's r = 0.96")+
  theme(plot.title = element_text(hjust = 0.5))
# 0.8426689 0.9622628

# xr_rrbs <- CorrelatePlot2(samp1=rep12.10cov_comb.15cov, samp2=k562_rrbs2_chr,
#                            assay_xr="FLEXseq, rep1&2", assay="RRBS", covnum=15) 
# xr_rrbs_2 <- xr_rrbs + ggtitle("Pearson's r = 0.96")+
#   theme(plot.title = element_text(hjust = 0.5))
# 0.8786946 0.9557302 

xr_rrbsv2 <- CorrelatePlot2(samp1=rep12.10cov_comb.15cov, samp2=k562_rrbs_2,
                           assay_xr="FLEXseq, rep1&2", assay="RRBS", covnum=15) 
xr_rrbsv2_2 <- xr_rrbsv2 + ggtitle("Pearson's r = 0.96")+
  theme(plot.title = element_text(hjust = 0.5))
# 0.8439486 0.9632171

xr_xrbs <- CorrelatePlot2(samp1=rep12.10cov_comb.15cov, samp2=k562_xrbs2_chr,
                           assay_xr="FLEXseq, rep1&2", assay="XRBS", covnum=15)   
xr_xrbs_2 <- xr_xrbs + ggtitle("Pearson's r = 0.91")+
  theme(plot.title = element_text(hjust = 0.5))
# 0.7788166 0.9115793 

pm_wgbs.enriched.othr2 <- ggarrange(wgbs_rrbsv2_2,xr_rrbsv2_2,wgbs_xrbs_2,xr_xrbs_2,
                 common.legend = TRUE, legend= "bottom",
                 nrow = 2, ncol = 2)
pm_wgbs.enriched.othr2

# dev.new()
# pdf(file=file.path(pathref,"Output/correlation",
#                    paste0(str_sub(Sys.Date(), start = 3), 
# "-WGBS.enriched_vsRR101nt.XRBS_15cov.pdf")),
#     width = 9.5, height = 3.2, useDingbats = FALSE)
# pm_wgbs.enriched.othr2
# dev.off()


```

# Input titrations of BF cfDNA

```{r chk input titrations}

GetDataCor <- function(pathtemp,f,ncov){
df1 <- fread(file.path(pathtemp,
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(df1) <- c("chr","start","end","meth.cnt","depth")

df2 <- as.data.frame(df1) %>% filter(depth>=ncov) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))
print(nrow(df2))
return(df2)
}

#15cov
BF3713dil250ng_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="BF3713dil250ngXR23B_comb",ncov=15)

BF3713dil100ng_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="BF3713dil100ngXR23B_comb",ncov=15)

BF3713dil10ng_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="BF3713dil10ngXR23B_comb",ncov=15)

BF3713dil1ng_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="BF3713dil1ngXR23B_comb",ncov=15)

BF3713dil250pg_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="BF3713dil250pgXR23B_comb",ncov=15)

BF3713dil100pg_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="BF3713dil100pgXR23B_comb",ncov=15)

##########################

p10ngvs1ng_15cov <- CorrelatePlot2(samp1=BF3713dil10ng_15cov, samp2=BF3713dil1ng_15cov, 
  assay_xr="Input 10ng", assay="Input 1ng", covnum=15)
p10ngvs1ng_15cov2 <- p10ngvs1ng_15cov + ggtitle("Pearson's r = 0.90")+
  theme(plot.title = element_text(hjust = 0.5))
#       rho       cor 
#0.8638411 0.8972064 #cov=15

p10ngvs250ng_15cov <- CorrelatePlot2(samp1=BF3713dil10ng_15cov, samp2=BF3713dil250ng_15cov, 
  assay_xr="Input 10ng", assay="Input 250ng", covnum=15)
p10ngvs250ng_15cov2 <- p10ngvs250ng_15cov + ggtitle("Pearson's r = 0.89")+
  theme(plot.title = element_text(hjust = 0.5))
#       rho       cor 
#0.8744668 0.8923540  #cov=15

p10ngvs100ng_15cov <- CorrelatePlot2(samp1=BF3713dil10ng_15cov, samp2=BF3713dil100ng_15cov, 
  assay_xr="Input 10ng", assay="Input 100ng", covnum=15)
p10ngvs100ng_15cov2 <- p10ngvs100ng_15cov + ggtitle("Pearson's r = 0.90")+
  theme(plot.title = element_text(hjust = 0.5))
#       rho       cor 
#0.8881856 0.9013358  #cov=15

p10ngvs250pg_15cov <- CorrelatePlot2(samp1=BF3713dil10ng_15cov, samp2=BF3713dil250pg_15cov, 
  assay_xr="Input 10ng", assay="Input 250pg", covnum=15)
p10ngvs250pg_15cov2 <- p10ngvs250pg_15cov + ggtitle("Pearson's r = 0.91")+
  theme(plot.title = element_text(hjust = 0.5))
#       rho       cor 
#0.8605951 0.909687 #cov=15

p10ngvs100pg_15cov <- CorrelatePlot2(samp1=BF3713dil10ng_15cov, samp2=BF3713dil100pg_15cov, 
  assay_xr="Input 10ng", assay="Input 100pg", covnum=15)
p10ngvs100pg_15cov2 <- p10ngvs100pg_15cov + ggtitle("Pearson's r = 0.93")+
  theme(plot.title = element_text(hjust = 0.5))
#       rho       cor 
#0.8931375 0.9263076 #cov=15


pm_bf3713 <- ggarrange(p10ngvs250ng_15cov2,p10ngvs100ng_15cov2,p10ngvs1ng_15cov2,
                 p10ngvs250pg_15cov2,p10ngvs100pg_15cov2,
                 common.legend = TRUE, legend= "bottom",
                 ncol = 3, nrow = 2)
pm_bf3713

# save(pm2,file=file.path(pathref,"Output/correlation", 
#                    paste0(str_sub(Sys.Date(), start = 3), "-BF3713dil.15cov_vs10ng.corr.RData")))

# dev.new()  
# pdf(file=file.path(pathref,"Output/correlation", 
#                    paste0(str_sub(Sys.Date(), start = 3), "-BF3713dil.15cov_vs10ng.corr.pdf")), 
#     width = 9.5, height = 2.7, useDingbats = FALSE)
# pm2
# dev.off() 

```

# Input titrations of FFPE tissue DNA

```{r FFPE}


GetDataCor <- function(pathtemp,f,ncov){
df1 <- fread(file.path(pathtemp,
                     paste0(f,"-merged.cov.SNPfiltered_clean.txt")),
                     quote="",sep="\t")
colnames(df1) <- c("chr","start","end","meth.cnt","depth")

df2 <- as.data.frame(df1) %>% filter(depth>=ncov) %>%
      mutate(chr_cpg_loc = paste0(chr,"_",start,"_",end),
             beta=round(meth.cnt/depth, digits=5))
print(nrow(df2))
return(df2)
}

#10cov
ffpe50_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="FFPE50XR23B_comb",ncov=15)
#6079610, cov=10
#4531803, cov=15

ffpe10_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="FFPE10XR23B_comb",ncov=15)
#6498662, cov=10
#5042679, cov=15
ffpe5_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="FFPE5XR23B_comb",ncov=15)
#5732418, cov=10
#4023812, cov=15
ffpe1_15cov <- 
  GetDataCor(pathtemp="D:/Jingru/deconv/Data/Upload_processed/methylation_call_benchmarks",
             f="FFPE1XR24A_comb",ncov=15)
#834532, cov=10
#220286, cov=15

p10ngvs50ng_15cov <- CorrelatePlot2(samp1=ffpe10_15cov, samp2=ffpe50_15cov, 
  assay_xr="Input 10ng", assay="Input 50ng", covnum=15)
p10ngvs50ng_15cov2 <- p10ngvs50ng_15cov + ggtitle("Pearson's r = 0.96")+
  theme(plot.title = element_text(hjust = 0.5))
#      rho       cor 
#0.8098801 0.9409763, cov=10
#0.8331132 0.9565296, cov=15

p10ngvs5ng_15cov <- CorrelatePlot2(samp1=ffpe10_15cov, samp2=ffpe5_15cov, 
  assay_xr="Input 10ng", assay="Input 5ng", covnum=15)
p10ngvs5ng_15cov2 <- p10ngvs5ng_15cov + ggtitle("Pearson's r = 0.96")+
  theme(plot.title = element_text(hjust = 0.5))
#0.8034191 0.9393047
#0.8268879 0.9557422, cov=15

p10ngvs1ng_15cov <- CorrelatePlot2(samp1=ffpe10_15cov, samp2=ffpe1_15cov, 
  assay_xr="Input 10ng", assay="Input 1ng", covnum=15)
p10ngvs1ng_15cov2 <- p10ngvs1ng_15cov + ggtitle("Pearson's r = 0.90")+
  theme(plot.title = element_text(hjust = 0.5))
#0.6844943 0.8979925 
#0.7113987 0.9022243


pm_ffpe_15cov <- ggarrange(p10ngvs50ng_15cov2,p10ngvs5ng_15cov2,p10ngvs1ng_15cov2,
                 common.legend = TRUE, legend= "bottom",
                 ncol = 3)
pm_ffpe_15cov

# dev.new()
# pdf(file=file.path(pathref,"Output/correlation",
#                    paste0(str_sub(Sys.Date(), start = 3), "-FFPE_titration_15cov.pdf")),
#     width = 7, height = 3.1, useDingbats = FALSE)
# pm_ffpe_15cov
# dev.off()

```