---
title: 'DNA concentrations and input'
author: 'Lauren Ahmann, Jingru Yu'
date: '2024-08-06'
output: html_document
---
# Load packages

```{r load_packages, warning=FALSE, message=FALSE}
rm(list=ls());gc()

# load paths
options(scipen=999999999)

library(dplyr)
library(tidyverse)
library(openxlsx)
library(data.table)
library(writexl)
library(ggpubr)
library(rstatix)

library(ggpmisc)
require(broom)
library(ggpubr) #ggarrange
library(ggplot2)
library(beeswarm)
library(RColorBrewer)
library(ggbeeswarm)
library(ggprism)

# laod paths
pathpro <- "D:/Jingru/deconv/Data/Upload_processed"
```


# Standard P2 input, suppTable 

```{r Fig S8a P2 Titration Graph}

P2 <- read.csv(file.path(pathpro,"QC","DNA_concentration_P2.csv"))

lm_model <- lm(human.reads...lambda.reads ~ actual.input, data = P2)
intercept <- coef(lm_model)[1]
slope <- coef(lm_model)[2]
rsquared <- summary(lm_model)$r.squared

#get model p-value
f <- summary(lm_model)$fstatistic
p <- pf(f[1],f[2],f[3],lower.tail=F)
p
#get coefficient p-value
summary(lm_model)$coefficients[,4] 

P2_linear <- 
  ggplot(P2, aes(x = actual.input, y = human.reads...lambda.reads)) +
  geom_point() +
  geom_line(size=1.5) + 
  geom_smooth(method=lm,na.rm = TRUE,se = FALSE, linetype="dashed", color = "#00BFC4") +
  stat_poly_eq(use_label(c("eq", "R2","P")),
               label.x = "left",
               formula = y ~ x, 
               parse = TRUE) +
  scale_x_continuous(breaks = seq(0, 1, by = 0.25), labels=seq(0, 1, by = 0.25), 
                     limits=c(0,1.2),expand= c(0,0)) +
  scale_y_continuous(limits=c(0,120),expand= c(0,0)) +
   theme(panel.background = element_blank(),
        #panel.grid.major = element_blank(),
        panel.grid.major = element_line(color = "grey80", linewidth = 0.5, linetype = 1),
        panel.border = element_rect(color="black",fill=NA),
        axis.text.y = element_text(size=15, face="bold"),
        axis.text.x = element_text(size=15, face="bold"),
        axis.title=element_text(size=15,face="bold"),
        legend.position="none",
        legend.title=element_blank(),
        panel.spacing = unit(0.2, "lines"))+ 
  labs(x = "Sample Input (ng)", y = "Reads ration (human/lambda DNA)")

P2_linear

# dev.new()
# pdf(file=file.path(
#     paste0(str_sub(Sys.Date(), start = 3),"-P2_linear.pdf")),
#     width = 3.5, height = 3.3, useDingbats = FALSE)
# P2_linear
# dev.off()

```

# Load concentration data

```{r}

samp_con <- read.xlsx(file.path(pathpro,"QC","DNA_concentration_SuppTable.xlsx"),
                      sheet=1, skipEmptyRows=FALSE, colNames = TRUE)
samp_con <- samp_con[!samp_con$`mean_ng/mL` %in% c("not sequenced","x"),]

samp_con_filter <- samp_con[!is.na(samp_con$`mean_ng/mL`) 
                     & samp_con$Ran.for.paper %in% c("x","z")
                     & samp_con$Ext.method=="SU" 
                     & samp_con$Used_in_paper=="y" ,]
table(samp_con_filter$Sample.Type.New) #panel b, after filtering

samp_con_filter1 <- 
  samp_con_filter[,c(3:9,12)] %>% 
  mutate_at(c("mean_ng/mL"), as.numeric)
samp_con_filter1 <- samp_con_filter1[!is.na(samp_con_filter1$`mean_ng/mL`),]

stat1 <- 
  as.data.frame(t(psych::describe(samp_con_filter1
                                  [samp_con_filter1$Sample.Type.New=="CSF","mean_ng/mL"],
                                  quant=c(.05,.1,.25,.5,.75,.90,.95))))

```

# DNA concentration by sample types

```{r Fig S8c Sample Type Input}

samp_con_filter2 <- within(samp_con_filter1, {
 Sample_tp <-  NA
  Sample_tp[Sample.Type.New %in% 
    c("FNA-Liver","FNA-LN","FNA-Lung",
      "FNA-Pancreas")] <- "FNA"
  Sample_tp[Sample.Type.New=="CSF"] <- "CSF"
  Sample_tp[Sample.Type.New=="ABDO"] <- "ABDO"
  Sample_tp[Sample.Type.New=="PLEU"] <- "PLEU"
  Sample_tp[Sample.Type.New=="OVAR"] <- "OVAR"
  Sample_tp[Sample.Type.New=="PELV"] <- "PELV"

})

re_order <- c("CSF", "FNA", "ABDO", "PLEU")

samp_con_filter2 <- 
  samp_con_filter2[!samp_con_filter2$Sample_tp %in% c("OVAR","PELV"),]
samp_con_filter2 <- samp_con_filter2[order(match(samp_con_filter2$Sample_tp, re_order)), ]

samp_con_filter3 <- samp_con_filter2 %>% 
  mutate(
  Sample_tp.f = factor(as.factor(Sample_tp),order=T, 
                                     levels = re_order),
  Dx_cat = ifelse(Dx.Category == "Micro",yes="Infection", no=Dx.Category),
  Dx_cat.f = factor(as.factor(Dx_cat),order=T,
                                levels=c("Cancer", "Autoimmune/Autoinflammatory", 
                                         "Infection", "Other", "Unknown"),
                                labels=c("Cancer", "Autoimmune/\nAutoinflammatory", 
                                         "Infection", "Others", "Unknown")))

res.kruskal_samp <- samp_con_filter3 %>% kruskal_test(`mean_ng/mL` ~ Sample_tp.f)
res.kruskal_samp
#  n  statistic  df   p  method
# 129	29.60725	3	0.00000167	Kruskal-Wallis

pwc2_samp <- samp_con_filter3 %>% 
  wilcox_test(`mean_ng/mL` ~ Sample_tp.f, p.adjust.method = "bonferroni")
pwc2_samp

# boxplot: input all samples 

my_comparisons <- list( c("CSF", "FNA"), c("CSF", "ABDO"),  c("CSF", "PLEU") )

p_inputAll <- ggplot(data=samp_con_filter3, 
                     aes(x = Sample_tp.f, y = `mean_ng/mL`, color=Sample_tp.f)) +
  geom_boxplot(width=0.7) +
  geom_beeswarm(priority="density",cex=2,size=1.7)+
  labs(y="DNA supernatant (ng/mL)",x=NULL)+ 
  scale_color_manual(values = c("#009392","#39B185","#9CCB86","#EEB479")) +
  scale_y_log10(
   breaks = c(0.1, 1, 10, 100, 1000,10000),labels = c(0.1, 1, 10, 100, 1000,10000),
   limits=c(0.1,1e5)) + #labels = scales::number_format(),
   theme(panel.background = element_blank(),
        #panel.grid.major = element_blank(),
        panel.grid.major.y = element_line(color = "grey80",
                                          linewidth = 0.5,
                                          linetype = 1),
        panel.border = element_rect(color="black",fill=NA),
        axis.text.x = element_text(size=15,face="bold"),
        axis.text.y = element_text(size=15,face="bold"),
        axis.title=element_text(size=15,face="bold"),
        legend.position="none",
        legend.title=element_blank()) +
  stat_compare_means(comparisons = my_comparisons, 
                     p.adjust.method = "bonferroni",label = "p.adj.signif")+ 
  stat_compare_means(label.y = 9000)  

p_inputAll  
    
# dev.new()
# pdf(file=file.path(
#     paste0(str_sub(Sys.Date(), start = 3),"-DNAconcentration_bySampleType.pdf")),
#     width = 3.5, height = 3.3, useDingbats = FALSE)
# p_inputAll 
# dev.off()

stat_df1 <- samp_con_filter3 %>% 
group_by(Sample_tp.f) %>%
  reframe(
    count = n(),
    mean = mean(`mean_ng/mL`, na.rm = TRUE),
    sd = sd(`mean_ng/mL`, na.rm = TRUE),
    median=median(`mean_ng/mL`, na.rm = TRUE),
    iqr=quantile(`mean_ng/mL`, na.rm = TRUE)
  )

```

# DNA concentration by Dx categories

```{r Fig S8d Input by Dx cat}
options(scipen = 999999999)
samp_con <- read.xlsx(file.path(pathpro,"QC","DNA_concentration_SuppTable.xlsx"),
                      sheet=1, skipEmptyRows=FALSE, colNames = TRUE)

samp_con_filter4 <- samp_con[samp_con$Ran.for.paper != "g" #not for the paper
                             & samp_con$Ext.method=="SU" #extract from SU
                             & !samp_con$`mean_ng/mL` %in% c("x","not sequenced")
                             & samp_con$Sample.Type.New == "CSF",] #117

samp_con_filter4 <- within(samp_con_filter4, {
 Sample_tp <-  NA
  Sample_tp[Sample.Type.New %in% 
    c("FNA-Liver","FNA-LN","FNA-Lung",
      "FNA-Pancreas")] <- "FNA"
  Sample_tp[Sample.Type.New=="CSF"] <- "CSF"
  Sample_tp[Sample.Type.New=="ABDO"] <- "ABDO"
  Sample_tp[Sample.Type.New=="PLEU"] <- "PLEU"
  Sample_tp[Sample.Type.New=="OVAR"] <- "OVAR"
  Sample_tp[Sample.Type.New=="PELV"] <- "PELV"

})

samp_con_filter5 <- 
  samp_con_filter4[,c(3:9,12,36)] %>% 
  mutate_at("mean_ng/mL", as.numeric) %>% 
  mutate(
  Sample_tp.f = factor(as.factor(Sample_tp),order=T, 
                                     levels = re_order),
  Dx_cat = ifelse(Dx.Category == "Micro",yes="Infection", no=Dx.Category),
  Dx_cat.f = factor(as.factor(Dx_cat),order=T,
                                levels=c("Autoimmune/Autoinflammatory", "Cancer", 
                                         "Infection", "Other", "Unknown"),
                                labels=c("Autoimmune/\nAutoinflammatory", "Cancer", 
                                         "Infection", "Others", "Unknown")))

res.kruskal <- samp_con_filter5 %>% kruskal_test(`mean_ng/mL` ~ Dx_cat.f)
res.kruskal
#  n  statistic  df   p  method
# 117      36.9     4 0.000000185 Kruskal-Wallis

pwc2 <- samp_con_filter5 %>% 
  wilcox_test(`mean_ng/mL` ~ Dx_cat.f, p.adjust.method = "bonferroni")
pwc2


#boxplot: input by dx cat
my_comparisons <- list( c("Cancer", "Autoimmune/\nAutoinflammatory"), 
                        c("Cancer", "Infection"),
                        c("Autoimmune/\nAutoinflammatory", "Infection"))

p_dxcat <- 
  ggplot(data=samp_con_filter5, aes(x = Dx_cat.f, y = `mean_ng/mL`, color=Dx_cat.f)) +
  geom_boxplot(width=0.6) +
  geom_beeswarm(priority="density",cex=2,size=1.7)+
  labs(y="DNA ng/mL (supernatant)",x=NULL)+
  scale_y_log10(labels = c(0.1, 1, 10, 100, 1000,10000),
                breaks = c(0.1, 1, 10, 100, 1000,10000), limits=c(0.1,1e5))+
  scale_color_manual(values = c("#7CCBA2","#46AEA0","#089099","#00718B","#045275"))+
  theme(panel.background = element_blank(),
        panel.grid.major.y = element_line(color = "grey80",
                                          linewidth = 0.5,
                                          linetype = 1),
        panel.border = element_rect(color="black",fill=NA),
        axis.text.x = element_text(size=15,face="bold",angle=35,hjust=1),
        axis.text.y = element_text(size=15, face="bold"),
        axis.title=element_text(size=15,face="bold"),
        legend.position="none",
        legend.title=element_blank()) +
  stat_compare_means(comparisons = my_comparisons, 
                     p.adjust.method = "bonferroni",label = "p.adj.signif")+ 
  stat_compare_means(label.y = 15000)  # Add comparisons p-value
p_dxcat

stat_df <- samp_con_filter5 %>% 
group_by(Dx_cat.f) %>%
  reframe(
    count = n(),
    mean = mean(`mean_ng/mL`, na.rm = TRUE),
    sd = sd(`mean_ng/mL`, na.rm = TRUE),
    median=median(`mean_ng/mL`, na.rm = TRUE),
    iqr=quantile(`mean_ng/mL`, na.rm = TRUE)
  )

```

# DNA concentration by qPCR Ct

```{r Fig_S8b_Ct}
options(scipen = 999999999)
qc <- read.xlsx(file.path(pathpro,"QC","DNA_concentration_qc.xlsx"),
                      sheet=1, skipEmptyRows=FALSE, colNames = TRUE)

qc1 <- qc[qc$Sample.Source=="CSF" & !is.na(qc$qPCR.Ct) & qc$qPCR.Ct!="indeterminate",]

qc1 <- qc1 %>%
  mutate(
         temp1=sapply(str_split(`NGS.Sample.Name`, "X",  n = 2), `[`, 1),
         temp2=sapply(str_split(temp1, "w|q",  n = 2), `[`, 1),
         temp3=ifelse(str_sub(temp2,-1,-1)=="v", as.numeric(gsub("\\D", "", temp1)),
                      substring(temp2, 3)),
         qPCR.Ct_n = as.numeric(qPCR.Ct))

qc1$temp3 <- ifelse(qc1$temp3=="3544","3544A",
                    (ifelse(qc1$temp3=="3539","3539A",(ifelse(
  qc1$temp3=="3545","3545A",qc1$temp3)))))

qc2 <- merge(qc1,samp_con[,c("BF","Ext.method","Total_counts_dedup","Ct_XR_Avg")],
             by.x="temp3",by.y="BF",all.x=T)
qc3 <- qc2[qc2$Ext.method=="SU" & !is.na(qc2$temp3),]
qc3$Ct_XR_Avg_n <- as.numeric(qc3$Ct_XR_Avg)
qc3$Total_counts_dedup_n <- as.numeric(qc3$Total_counts_dedup)

#subset to extracted at SU
#samples not included in study

qc3 <- within(qc3, {
  grp <- NA
  grp[Ct_XR_Avg_n <=14 & Total_counts_dedup_n >=30000000] <- "Ct<=14, >=30M Reads"
  grp[Total_counts_dedup_n <30000000] <- "<30M Reads"
  grp[Ct_XR_Avg_n >14] <- "Ct>14"
})


lm_qc <- lm(log(`Sample.DNA.Concentration.(ng)`) ~ qPCR.Ct_n, data = qc3)
interceptQC <- coef(lm_qc)[1]
slopeQC <- coef(lm_qc)[2]
cat("y = exp(", round(interceptQC, 2), ") * exp(", round(slopeQC, 2), "x)")
rsquaredngvsCt <- summary(lm_qc)$r.squared
rsquaredngvsCt
#get model p-value
f <- summary(lm_qc)$fstatistic
p <- pf(f[1],f[2],f[3],lower.tail=F)
p
#get coefficient p-value
summary(lm_qc)$coefficients[,4]  
  
p_input3 <- ggplot(data = qc3, aes(x = qPCR.Ct_n, y = `Sample.DNA.Concentration.(ng)`,color=grp)) +
  geom_jitter(width = 0.25, height = 0.0, size = 1.5) +
  geom_smooth(method=lm,na.rm = TRUE,se = FALSE, linewidth=1.3,color="black",aes(group = 1)) +
  scale_color_manual(values = c("#FFAA00","#00B000","#e9002D")) +
  labs(y = "DNA input (ng)", x = "Ct") +
  scale_y_continuous(trans = "log10", breaks = c(0.1, 1,10,100),
  label = c(0,1,10,100),limits=c(0.1,150),expand=c(0,0)) +
  scale_x_continuous(breaks = seq(6, 15, by = 1),limits=c(5,16),expand=c(0,0))+
  theme(panel.background = element_blank(),
        panel.grid.major = element_line(color = "grey80", linewidth = 0.5, linetype = 1),
        panel.border = element_rect(color = "black", fill = NA),
        axis.text.x = element_text(size = 15, face = "bold"),
        axis.text.y = element_text(size = 15, face = "bold"),
        axis.title = element_text(size = 15, face = "bold"),
        legend.position = "inside", 
        legend.position.inside = c(0.8, 0.8),
        legend.title = element_blank(),
        legend.text = element_text(size=6),
        panel.spacing = unit(0.2, "lines"))

p_input3

# dev.new()
# pdf(file=file.path(
#     paste0(str_sub(Sys.Date(), start = 3),"-DNAinputvs.Ct_linear.pdf")),
#     width = 4, height = 3.3, useDingbats = FALSE)
# p_input3
# dev.off()

```
