---
title: "pheatmap_clinical"
author: "Jingru Yu"
date: '2024-02-06'
output: html_document

update1: '2024-05-06' #change prediction labels
update2: '2024-08-13' #update sample types
---

# Load package

```{r load_packages, warning=FALSE, message=FALSE}
rm(list=ls())
library(dplyr)
library(tidyverse)
library(stringr)
library(openxlsx)
library(data.table) #detDT
library(scales)
library(writexl) 
library(matrixStats) #colMeans, colMedians
library(rstatix)

# Load the pheatmap package
library (pheatmap)
library(Hmisc) #describe
library(ComplexHeatmap)
library(ggplot2)
library(ggbreak) #scale_y_break
library(cowplot) #ggdraw, a simple add-on to ggplot
library(ggrepel) #geom_text_repel
library(ggforce) # for 'geom_arc_bar'
library(ggrepel)
library(ggpubr) #ggarrange
library(beeswarm)
library(RColorBrewer)
library(ggbeeswarm)

library(pROC)     # estimate / display prediction performance
library(ROCR)
library(vip)      # for variable importance plots
library(metrica)
library(purrr)

library(ggpmisc) #add regression equations
require(broom)

# load paths
pathpro <- "D:/Jingru/deconv/Data/Upload_processed"
```

# import dataset

```{r Age}
samp_res_final2 <- 
  read.xlsx(file.path(pathpro,"clinical_info","24-06-24-185samples_res_final_improve.xlsx"),
                      sheet=1, skipEmptyRows=FALSE, colNames = TRUE)
samp_res_final2$ca_co <- 
  ifelse(samp_res_final2$Sample_type=="CSF" & samp_res_final2$Diag_TCGA=="Control", 
         "Control","Case")
or_tp <- c("CSF", "non-CSF BF", "FFPE")
or_caco <- c("Control", "Case")
samp_res_final3 <- samp_res_final2 %>% 
    arrange(factor(Sample_tp.3cat, levels = or_tp))%>% 
    arrange(factor(ca_co, levels = or_caco))

samp_res_final3$TCGA_Project <- ifelse(samp_res_final3$BF_id=="BF3020","Angiosarcoma",
                                       samp_res_final3$TCGA_Project)
samp_res_final3$TCGA_Project_subgrp <- ifelse(samp_res_final3$BF_id=="BF3020","Angiosarcoma",
                                       samp_res_final3$TCGA_Project_subgrp)
samp_res_final3$TCGA_Project_mcf <- ifelse(samp_res_final3$BF_id=="BF3020","Angiosarcoma",
                                       samp_res_final3$TCGA_Project_mcf)
samp_res_final3$Path_diagnosis <- ifelse(samp_res_final3$BF_id=="BF3020","Angiosarcoma",
                                       samp_res_final3$Path_diagnosis)
samp_res_final3$Diag_TCGA <- ifelse(samp_res_final3$BF_id=="BF3020","Angiosarcoma",
                                       samp_res_final3$Diag_TCGA)

samp_res_final3$Path_diagnosis <- ifelse(samp_res_final3$Path_diagnosis=="Control","Negative",
                                       samp_res_final3$Path_diagnosis)

#CSF
samp_res_csf <- samp_res_final3[samp_res_final3$Sample_type=="CSF",] 


ca <- samp_res_final3[samp_res_final3$ca_co=="Case" & samp_res_final3$Sample_type=="CSF",]
co <- samp_res_final3[samp_res_final3$ca_co=="Control",]

quantile(ca$Age)
quantile(co$Age)
wilcox.test(Age ~ ca_co, data = samp_res_final3[samp_res_final3$Sample_type=="CSF",])
#W = 1934.5, p-value = 0.0007227

mtab <- table(samp_res_csf$Sex,samp_res_csf$ca_co)
chisq.test(mtab) # Prints test summary

```

# pheatmap for CSF

```{r pheatmap_CSF}
samp_res_csf <- samp_res_final3[samp_res_final3$Sample_type=="CSF",]
samp_res_csf <- samp_res_csf[order(samp_res_csf$purity.abs),]

rm(.Random.seed, envir=globalenv())

set.seed (23951)
meth <- matrix (rnorm (212), nrow = 2, ncol = 106)
colnames(meth) <- paste0("Sample_", 1:106)
rownames (meth) <- paste0 ("Gene_", 1:2)

# Create a data frame of sample information
# Each row is a sample and each column is a variable

colnames(meth) <- samp_res_csf$BF_id
row.names(samp_res_csf) <- colnames(meth)

ann_colors = list(
  `CNA calls` = c(`+`="gray15", `-`="white"),
  `ML classification`=c("Misleading profile"="#cc0000", "Indeterminate"="grey70",
                   "Matched"="#18A558", "Reference"="#1461f0",#1461f0 #057DCD
                   "Matched to GI-AD family"="#8FA01F",
                   "Matched to GYN family"="#8BCD50",
                   "N/a"="white"), 
  `Path. diagnosis`=c(
    "BRCA"="#c95f7b","COAD"="#ad6ef1","Negative"="white",
    "DLBC"="#e98c61","LUAD"="#b890e0","STAD"="#f79246","OV/UCS"="#0581be",
    "GBM"="#44aeff","GBM/PXA"="#44aeff",
    "MB"="#68ab97","O IDH"="#ffe336"), 
  `Deconv. classification`=c("N/a"="white", "Reference"="#1461f0",
                             "Misleading profile"="#cc0000",
                 "Matched"="#18A558", "Indeterminate"="grey70"), #"CNA (-)"="#ff8200"
  `Composite classification`=c("Misleading profile"="#cc0000", "Indeterminate"="grey70",
              "Matched"="#18A558", "Matched to GI-AD family"="#8FA01F",
              "Negative"="#E6AB02","N/a"="white"),
  Sex = c("M" = "#1461f0", "F" = "#d30202", "N/a"="white"),
  #Age = c("white", "#378561")
  `Cytology` = c("Positive"="#18A558","Atypical/Suspicious"= "grey70",
                 "Negative"= "#E6AB02", "N/a"="white" ),
  `Flow cytometry` = c("Positive"="#18A558","Atypical/Suspicious"= "grey70",
                 "Negative"= "#E6AB02", "N/a"="white" )
  )

dot_anno <- anno_points(samp_res_csf$TF_XR, pt_size = unit(0.7, "mm"))  

# Define the annotations for columns
anno <- HeatmapAnnotation(
  Age=samp_res_csf$Age,
  Sex=samp_res_csf$Sex,
  `Cytology`=samp_res_csf$cyto_clean,
  `Flow cytometry`=samp_res_csf$flow_clean,
  `CNA calls`=samp_res_csf$CNA_calls,
  `Tumor fraction`=dot_anno,
  `Path. diagnosis`=samp_res_csf$Path_diagnosis,
  `ML classification`=samp_res_csf$Classification,
  `Deconv. classification`=samp_res_csf$Deconvolution,
  `Composite classification`=samp_res_csf$Composite,
  gp = gpar(col = "gray40"),
  col = ann_colors, # Ensure 'ann_colors' is defined correctly to match categories
  which = "col", # Annotation for columns
  show_annotation_name = TRUE, # Show names of the annotations
  show_legend = c(FALSE, FALSE, FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)
)

aa1 <- Heatmap(as.matrix(meth), # The data matrix
  name = "Methylation Level", # Title of the heatmap
  top_annotation = anno, # Add annotations at the top
  row_title = "Rows", # Title to the side of rows
  show_column_names = TRUE, # Whether to show column names
  show_row_names = FALSE, # Whether to show row names
  border = TRUE,
  cluster_rows = FALSE, # Disable row clustering
  cluster_columns = FALSE # Disable column clustering
)
aa1


```

# pheatmap for non-CSF and FFPE

```{r pheatmap_nonCSF}
samp_res_othr <- samp_res_final3[samp_res_final3$Sample_type!="CSF",]
samp_res_othr <- samp_res_othr[order(samp_res_othr$purity.abs),]
or_target <- c("non-CSF BF", "FFPE")
samp_res_othr2 <- samp_res_othr %>% 
    arrange(factor(Sample_tp.3cat, levels = or_target))

rm(.Random.seed, envir=globalenv())

set.seed (1259)
meth <- matrix (rnorm (158), nrow = 2, ncol = 79)
colnames(meth) <- paste0("Sample_", 1:79)
rownames (meth) <- paste0 ("Gene_", 1:2)

# Create a data frame of sample information
# Each row is a sample and each column is a variable

colnames(meth) <- samp_res_othr2$BF_id
row.names(samp_res_othr2) <- colnames(meth)

ann_colors = list(
  `CNA calls` = c(`+`="gray15", `-`="white"),
  `Sample type` = c("non-CSF BF" = "#ef767a","FFPE"="#49beaa"),
  `ML classification`=c("Misleading profile"="#cc0000", "Indeterminate"="grey70",
                   "Matched"="#18A558", #1461f0 #057DCD
                   "Matched to GI-AD family"="#8FA01F",
                   "Matched to GYN family"="#8BCD50",
                   "N/a"="white"), #,"NA"="gray100",
  `Path. diagnosis`=c(
    "BRCA"="#c95f7b","COAD"="#ad6ef1","Negative"="white",
    "DLBC"="#e98c61","ESCA"="#7af870","HNSC"="#55c056","KIRC"="#9d5723",
    "NSCLC"="#b890e0","LIHC/CHOL"="#fa8fcc","LUAD"="#b890e0","LUSC"="#27780d",
    "OV"="#0581be","OV/UCEC"="#f50a41","PAAD"="#734ba9","PNET"="#a37c92",
    "SKCM"="#63632f","Angiosarcoma"="#b1b197","STAD"="#f79246","TGCT"="#ddca11",
    "UCEC"="#43dad7", "EPN, RELA"="#973534","GBM"="#44aeff",
    "MB, G4"="#0581be","MB, SHH INF"="#8bc0ff",
    "MB, WNT"="#6da7d9","MNG"="#d566d7","O IDH"="#ffe336"), 
  `Deconv. classification`=c("N/a"="white", "Misleading profile"="#cc0000",
                 "Matched"="#18A558", "Indeterminate"="grey70"),
  `Composite classification`=c(
    "Misleading profile"="#cc0000", "Indeterminate"="grey70",
    "Matched"="#18A558", "Matched to GI-AD family"="#8FA01F",
    "Matched to GYN family"="#8BCD50",
    "Negative control"="#6da7d9","N/a"="white"),
  Sex = c("M" = "#1461f0", "F" = "#d30202", "N/a"="white"),
  `Cytology` = c("Positive"="#18A558","Atypical/Suspicious"= "grey70",
                 "Negative"= "#E6AB02", "N/a"="white" ),
  `Flow cytometry` = c("Positive"="#18A558","Atypical/Suspicious"= "grey70",
                 "Negative"= "#E6AB02", "N/a"="white" )
  )

dot_anno <- anno_points(samp_res_othr2$TF_XR, pt_size = unit(0.75, "mm"))  

# Define the annotations for columns
anno <- HeatmapAnnotation(
  `Sample type`=samp_res_othr2$Sample_tp.3cat,
  Age=samp_res_othr2$Age,
  Sex=samp_res_othr2$Sex,
  `Cytology`=samp_res_othr2$cyto_clean,
  #`Flow cytometry`=samp_res_othr2$flow_clean,
  `CNA calls`=samp_res_othr2$CNA_calls,
  `Tumor fraction`=dot_anno,
  `Path. diagnosis`=samp_res_othr2$Path_diagnosis,
  `ML classification`=samp_res_othr2$Classification,
  #Deconvolution=samp_res_othr$Deconvolution,
  #Composite=samp_res_othr$Composite,
  gp = gpar(col = "gray40"),
  col = ann_colors, # Ensure 'ann_colors' is defined correctly to match categories
  which = "col", # Annotation for columns
  show_annotation_name = TRUE, # Show names of the annotations
  show_legend = c(FALSE, FALSE, FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)
)

aa2 <- Heatmap(as.matrix(meth), # The data matrix
  name = "Methylation Level", # Title of the heatmap
  top_annotation = anno, # Add annotations at the top
  row_title = "Rows", # Title to the side of rows
  show_column_names = TRUE, # Whether to show column names
  show_row_names = FALSE, # Whether to show row names
  border = TRUE,
  cluster_rows = FALSE, # Disable row clustering
  cluster_columns = FALSE # Disable column clustering
)

aa2

```

# Make ROC curve
#remove indeterminate cases

```{r ROC}

options(scipen = 999999999)
load(file=file.path(pathpro,"TCGA-CNStumor_training_results",
                    "T3-validation.cv.score.k5_1019test_169TCGA.XR.RData"))

GetROCvalue <-  function(res_df, class_index){
bi_pred <- as.data.frame(probs[res_df$Sentrix_ID, class_index])
colnames(bi_pred)<-"bi_pred"
bi_pred$Sentrix_ID <- rownames(bi_pred)

obs_lab <- ifelse(res_df$Diag_TCGA==class_index, 1,0)

res_df$obs_lab <- ifelse(res_df$Diag_TCGA==class_index, 1,0)
class_mat <- merge(bi_pred,res_df[,c("Sentrix_ID","obs_lab")],by="Sentrix_ID")
colnames(class_mat) <- c("Sentrix_ID","pred","obs")

# ROC using pROC
luad_class <- pROC::roc(response = class_mat$obs, predictor = class_mat$pred, ci=TRUE)
# luad_class$auc
# luad_class$ci

deconv_pred <- 
  ifelse(res_df$pred_deconv==class_index, 1,0)

deconv_mat <- data.frame(obs=obs_lab, pred=deconv_pred, Sentrix_ID=res_df$Sentrix_ID)

luad_deconv <- pROC::roc(response = deconv_mat$obs, predictor = deconv_mat$pred, ci=TRUE)

comb_mat <- class_mat
colnames(comb_mat) <- c("Sentrix_ID","pred_class","obs_class")

comb_mat2 <- merge(comb_mat,deconv_mat,by="Sentrix_ID")
colnames(comb_mat2)[5] <- "pred_deconv"

comb_mat_pur <- 
  merge(comb_mat2,res_df
        [,c("Sentrix_ID","purity.abs","top1_cal_label","top1_cal_score","pred_comb")])

comb_mat_pur <- comb_mat_pur %>% 
  mutate(pred = ifelse(purity.abs>=0.5 & top1_cal_label!="Control" 
                            & top1_cal_score>=0.3, pred_class, pred_deconv),
         pred2 = ifelse(pred_comb==class_index, 1,0))

luad_comb <- pROC::roc(response = comb_mat_pur$obs, predictor = comb_mat_pur$pred,ci=TRUE)

return(list(luad_class,luad_deconv,luad_comb))

}
table(samp_res_csf$CNA_calls)
table(samp_res_csf$pred_deconv)

res_csf_noCNS.novuage <- samp_res_csf[samp_res_csf$CNA_calls=="+" #53
                               & (samp_res_csf$pred_deconv !="Indeterminate" #7
                                   & samp_res_csf$pred_classification!="Indeterminate"),]
#46 cases
luad_roc <- GetROCvalue(res_df=res_csf_noCNS.novuage, class_index="LUAD")
brca_roc <- GetROCvalue(res_df=res_csf_noCNS.novuage, class_index="BRCA")
lympho_roc <- GetROCvalue(res_df=res_csf_noCNS.novuage, class_index="DLBC")

#make graph

par(mfrow=c(1,3), mar=c(0.07,0.07,1,1)) 

plot(luad_roc[[1]], 
     xlab = "Specificity", ylab = "Sensitivity", 
     col="blue", lty=3,  print.auc = TRUE, 
     print.auc.x = 0.9, print.auc.y = 0.2)
plot(luad_roc[[2]], add = TRUE, colorize = TRUE, col="#d30202",lty=4,  
     print.auc = TRUE, print.auc.x = 0.9, print.auc.y = 0.6)
plot(luad_roc[[3]], add = TRUE, colorize = TRUE, col="gray20", lty=1,  
     print.auc = TRUE, print.auc.x = 0.9, print.auc.y = 0.4)
text(x = 0.5, y = 1.1,labels = "LUAD", xpd = NA)

plot(lympho_roc[[1]], 
     col="blue", lty=3,  print.auc = TRUE, 
     print.auc.x = 0.9, print.auc.y = 0.2)
plot(lympho_roc[[2]], add = TRUE, colorize = TRUE, col="#d30202",lty=4,  
     print.auc = TRUE, print.auc.x = 0.9, print.auc.y = 0.6)
plot(lympho_roc[[3]], add = TRUE, colorize = TRUE, col="gray20", lty=1, 
     print.auc = TRUE, print.auc.x = 0.9, print.auc.y = 0.4)
text(x = 0.5, y = 1.1,labels = "DLBC", xpd = NA)

plot(brca_roc[[1]],
     col="blue", lty=3,  print.auc = TRUE,
     print.auc.x = 0.9, print.auc.y = 0.2)
plot(brca_roc[[2]], add = TRUE, colorize = TRUE, col="#d30202",lty=4,
     print.auc = TRUE, print.auc.x = 0.9, print.auc.y = 0.6)
plot(brca_roc[[3]], add = TRUE, colorize = TRUE, col="gray20", lty=1,
     print.auc = TRUE, print.auc.x = 0.9, print.auc.y = 0.4)
text(x = 0.5, y = 1.1,labels = "BRCA", xpd = NA)

```

# Confusion matrix

```{r Confusion matrix}
samp_res_csf1 <- 
  samp_res_final3[samp_res_final3$Sample_type=="CSF"
                & samp_res_final3$pred_comb !="Indeterminate",]

samp_res_csf1$pred_comb <-
  ifelse(samp_res_csf1$pred_comb=="OV","OV/UCS",samp_res_csf1$pred_comb)
samp_res_csf1$Diag_TCGA <-
  ifelse(samp_res_csf1$Diag_TCGA=="OV","OV/UCS",samp_res_csf1$Diag_TCGA)

table(samp_res_csf1$Composite)
table(samp_res_csf1$pred_comb)
#c("MCF GBM", "MCF IDH GLM", "MCF MB G3G4", "MCF MB SHH", Brain)

con_matrix <- table(True=samp_res_csf1$Diag_TCGA, Predicted = samp_res_csf1$pred_comb)
con_df <- as.data.frame(con_matrix)
colnames(con_df)


lab_true <- names(table(con_df$True))
lab_pred <- names(table(con_df$Predicted))


# a2 <- data.frame(True=rep("Brain (U)",times=12), 
#                  Predicted=c(lab_pred,"MCF IDH GLM","STAD"),
#                  Freq=rep(0,times=12))

a3 <- data.frame(True=rep("Kidney",times=11), 
                 Predicted=c(lab_pred,"MCF IDH GLM","STAD"),
                 Freq=rep(0,times=11))
a4 <- data.frame(True=c(lab_pred,"MCF IDH GLM","STAD"),
                 Predicted=rep("STAD",times=11),
                 Freq=rep(0,times=11))
a5 <- data.frame(True=c(lab_pred,"MCF IDH GLM","STAD"),
                 Predicted=rep("MCF IDH GLM",times=11),
                 Freq=rep(0,times=11))

con_df_m <- rbind(con_df,a3,a4,a5)
con_df_m <- unique(con_df_m)

con_df_m2 <- con_df_m %>%
  mutate(True_char=as.character(True),
         Pred_char=as.character(Predicted),
         Pred_f=factor(as.factor(Pred_char),order=T,
                       levels=c("Control","BRCA","COAD","DLBC","Kidney","LUAD",
                                "STAD","OV/UCS","MCF GBM","MCF IDH GLM","MCF MB G3G4"),
                       labels=c("Negative","BRCA","COAD","DLBC","Kidney tumor","LUAD",
                                "STAD","OV/UCS","MCF GBM","MCF IDH GLM","MCF MB G3G4")),
         True_f=factor(as.factor(True_char),order=T,
                       levels=c("MCF MB G3G4","MCF IDH GLM","MCF GBM",
                                "OV/UCS","STAD","LUAD","Kidney","DLBC","COAD","BRCA","Control"),
                       labels=c("MCF MB G3G4","MCF IDH GLM","MCF GBM",
                                "OV/UCS","STAD","LUAD","Kidney tumor","DLBC","COAD","BRCA","Negative")),
         col_grp=ifelse(True_char==Pred_char,1,ifelse(True_char!=Pred_char & Freq!=0, 2,0)),
         col_grp_f=factor(as.factor(col_grp),
                          levels=c(1,2,0),
                          labels=c("Correct classification","Misclassified","No cases")))


#plot
pmat <- ggplot(con_df_m2, aes(x = Pred_f, y = True_f, fill = col_grp_f)) +
  geom_tile(color = "black") +
  labs(x = "Composite classification", y = "Path. diagnosis", title = NULL) +
  geom_text(aes(label = Freq), vjust = 1, color="black") +
  #scale_fill_gradient(low = "white", high = "blue") +
  scale_fill_manual(values = c("#2979FF","#cc0000",'transparent')) + #"#0202d390"
  theme_minimal() +
  scale_x_discrete(position = "top") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        axis.text.x = element_text(size=12, face="bold",angle=90),
        axis.text.y = element_text(size=12, face="bold"),
        axis.title.x = element_text(face="bold", size = 13),
        axis.title.y = element_text(face="bold", size = 13),
        legend.position = "none")

pmat

```

# Extended Data Figure, tumor fraction vs. others

```{r TF vs.zscore}
samp_res_csf.ca2 <- samp_res_final3[samp_res_final3$Sample_type=="CSF"
                                  & samp_res_final3$CNA_calls=="+",] #53

#=================
#z score vs. TF
#samp_res_csf.ca2[!is.na(samp_res_csf.ca2$deconv_prop),]
res_ca2 <- samp_res_csf.ca2 %>%
  mutate(TF_50grp = ifelse(TF_XR<0.5, 1,2),
         TF_50grp = ifelse(BF_id=="BF3792", 2, TF_50grp),
         TF_XR = ifelse(BF_id=="BF3792", 0.5, TF_XR),
         TF_50grp.f = factor(as.factor(TF_50grp), order=T,
                levels=c(1,2),labels=c("<50%","50%+")))

#remove 4 samples with wrong deconv results
pz <- ggplot(res_ca2, aes(x=TF_XR, y=top1_zscore, color=TF_50grp.f)) +
  geom_point() + 
  geom_smooth(method=lm,na.rm = TRUE) +
  stat_poly_eq(use_label(c("eq", "R2","P")),
               label.x = "right",
               formula = y ~ x, 
               parse = TRUE) +
  scale_color_manual(values=c("#6497b1","#005b96")) +
  geom_vline(xintercept = 0.5, linetype="dotted", color = "gray80", size=1) +
  geom_hline(yintercept = 2, linetype="dashed", color = "gray20", size=1) +
  geom_hline(yintercept = 3, linetype="dashed", color = "gray70", size=1) +
  labs(x = "Tumor purity", y = "Z score") +
  scale_x_continuous(breaks=seq(0, 1, by = 0.2),
                     labels=seq(0, 1, by = 0.2), limits=c(-0.005,1), expand = c(0, 0)) + 
  scale_y_continuous(breaks=seq(0, 40, by = 10),
                     labels=seq(0, 40, by = 10), limits=c(-0.01,40), expand = c(0, 0)) + 
  theme(panel.background = element_blank(),
        #panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.border = element_rect(color="black",fill=NA),
        text=element_text(size=14, face="bold"),
        axis.text.x = element_text(size=14,face="bold"),
        axis.text.y = element_text(size=14, face="bold"),
        axis.title=element_text(size=14,face="bold"),
        legend.position="none",
        legend.title=element_blank()) 
pz


```

# Extended Data Figure, array vs. XR

```{r check all scores}
score_all1 <- 
  read.xlsx(file.path(pathpro,"TCGA-CNStumor_training_results",
  "T3-score.comp.k5_TCGA_1019test_169TCGA.XR.xlsx"),
                      sheet=1, skipEmptyRows=FALSE, colNames = TRUE)

table(score_all1$grp)
anno_add_cns <- read.xlsx(file.path(pathpro,"clinical_info","sample_info_clean.xlsx"),
                       sheet=3, skipEmptyRows=FALSE, colNames = TRUE)
rm_cns <- anno_add_cns[1:6,"TCGA_ID"]

rm_all <- c(rm_cns,"BF3713dil100ngXR23B","BF3713dil1ngXR23B","BF3713dil250ngXR23B")

score_all2 <- score_all1[!score_all1$TCGA_ID %in% rm_all,]
table(score_all2$grp)


samp_clin <- read.xlsx(file.path(pathpro,"clinical_info",
                              "206samples_all_clin_clean.xlsx"),
                    sheet=1, skipEmptyRows=FALSE, colNames = TRUE)
samp_clin2 <- samp_clin[,c("TCGA_ID","Sample_type")]

samp_clin2 <- within(samp_clin2, {
 Sample_tp.3cat <-  NA
  Sample_tp.3cat[Sample_type %in% 
    c("ABDO","BAL","FNA-Liver","FNA-LN","FNA-Lung",
      "FNA-Pancreas","OVAR","PELV","PLEU")] <- "non-CSF BF"
  Sample_tp.3cat[Sample_type=="CSF"] <- "CSF"
  Sample_tp.3cat[substr(Sample_type,1,4)=="FFPE"] <- "FFPE"
  Sample_tp.3cat[Sample_type=="Titration"] <- "gDNA"
})


score_all3 <- merge(score_all2,samp_clin2[,c(1,3)],by="TCGA_ID", all.x=T)
score_all3 <- score_all3 %>% 
  mutate(Sample_tp.3cat=ifelse(grp=="Array","Array",Sample_tp.3cat),
         purity.abs=ifelse(TCGA_ID =="BF3792XR23B",
                           0.50,purity.abs),
         TF_50grp = ifelse(purity.abs<0.1, 1, (ifelse(purity.abs>=0.1 & purity.abs<0.5,2,3))),
         TF_50grp.f = factor(as.factor(TF_50grp), order=T,
                levels=c(1,2,3),labels=c("<0.1","0.1-0.5","0.5+")),
         Sample_tp.3cat.f=factor(as.factor(Sample_tp.3cat), order=T,
                levels=c("Array","CSF","non-CSF BF","FFPE","gDNA"),
                labels=c("Array","CSF","Non-CSF BF","FFPE","gDNA")))

stat_df <- score_all3 %>% 
group_by(Sample_tp.3cat) %>%
  summarise(
    count = n(),
    mean = mean(top1_cal_score, na.rm = TRUE),
    sd = sd(top1_cal_score, na.rm = TRUE)
  )

stat_df2 <- score_all3 %>% 
group_by(Sample_tp.3cat,TF_50grp) %>%
  summarise(
    count = n(),
    mean = mean(top1_cal_score, na.rm = TRUE),
    sd = sd(top1_cal_score, na.rm = TRUE),
    median_purity=median(purity.abs, na.rm = TRUE)
  )

score_all4 <- score_all3[!score_all3$Sample_tp.3cat.f %in% c("CSF","Array")
                         & score_all3$TF_50grp==3,]

# Compute the analysis of variance
res_kw <- kruskal_test(top1_cal_score ~ Sample_tp.3cat, data = score_all4[score_all4$TF_50grp==3,])
summary(res_kw)

pwc2 <- score_all4 %>% 
  wilcox_test(top1_cal_score ~ Sample_tp.3cat, p.adjust.method = "bonferroni")
pwc2

#make violin plot
score_predcan <- score_all3[!score_all3$Sample_tp.3cat.f %in% c("CSF","Array") &
                                        score_all3$top1_cal_label!="Control",]
score_predcan$TF_50grp.f = factor(as.factor(score_predcan$TF_50grp), order=T,
                levels=c(2,3),labels=c("<0.5","0.5+"))
table(score_predcan$Sample_tp.3cat)

pwc4 <- score_predcan %>% 
  wilcox_test(top1_cal_score ~ TF_50grp.f, p.adjust.method = "bonferroni")
pwc4
#top1_cal_score <50%   50%+      12    39       113 0.00628


#add
p_score_othr <- ggplot(data=score_predcan,
                  aes(x = TF_50grp.f, y = top1_cal_score, color=TF_50grp.f)) +
  geom_violin(trim=T, position=position_dodge(1),drop = FALSE) +
  geom_quasirandom(dodge.width=0.4,varwidth=TRUE) +
  scale_color_manual(values=c("#F8766D","#00BFC4"))+
  labs(y="Calibrated score",x="Tumor purity")+
  facet_wrap( ~ Sample_tp.3cat.f, ncol=4)+
  theme(panel.background = element_blank(),
        #panel.grid.major = element_blank(),
        panel.grid.major.y = element_line(color = "grey80",
                                          linewidth = 0.5,
                                          linetype = 1),
        panel.border = element_rect(color="black",fill=NA),
        #text=element_text(size=15, face="bold"),
        axis.text.x = element_text(size=15,face="bold", angle=30,hjust=1),
        axis.text.y = element_text(size=15, face="bold"),
        axis.title=element_text(size=15,face="bold"),
        strip.text = element_text(size = 14,face="bold"),
        legend.position="none",
        legend.title=element_blank()) 
p_score_othr
  

```

# Other sample type distribution

```{r barchart of other samples}

samp_bf <- samp_res_final3[!samp_res_final3$Sample_type %in% c("CSF","Titration")
                           & samp_res_final3$Sample_tp.3cat!="FFPE"
                   & !samp_res_final3$TCGA_ID %in% 
                     c("BF3713dil250ngXR23B","BF3713dil100ngXR23B","BF3713dil1ngXR23B"),]
stat_bf <- as.data.frame(table(samp_bf$Sample_type))

hist_bf <- ggplot(data=samp_bf, aes(x=Sample_type)) +
  geom_bar()+
  labs(y="Count",x=NULL,title="Non-CSF BF")+
    scale_y_continuous(breaks=seq(0, 25, by = 5),
                     labels=seq(0, 25, by = 5), limits=c(0,26), expand=c(0,0)) + 
   theme(panel.background = element_blank(),
        #panel.grid.major = element_blank(),
        panel.grid.major.y = element_line(color = "grey80",
                                          size = 0.5,
                                          linetype = 1),
        panel.border = element_rect(color="black",fill=NA),
        #text=element_text(size=15, face="bold"),
        axis.text.x = element_text(size=15,face="bold",angle=30,hjust=1),
        axis.text.y = element_text(size=15, face="bold"),
        axis.title=element_text(size=15,face="bold"),
        legend.position="none",
        legend.title=element_blank(),
        plot.title = element_text(hjust = 0.5,size=15,face="bold"))

hist_bf 


#FFPE
samp_ffpe <- samp_res_final3[samp_res_final3$Sample_tp.3cat=="FFPE",]

samp_ffpe1 <- samp_ffpe %>% 
mutate(diag_grp = 
  ifelse(TCGA_Project %in% 
           c("EPN, RELA","MB, WNT","MCF GBM","MCF IDH GLM","MCF MB G3G4",  
             "MCF MB SHH","MNG"), "Brain", TCGA_Project),
  organ = sapply(str_split(Sample_type, " - ",  n = 2), `[`, 2))


stat_ffpe <- as.data.frame(table(samp_ffpe1$organ))
print(stat_ffpe$Var1)
table(samp_ffpe1$organ)
#tissue source?

samp_ffpe2 <- merge(samp_ffpe1,stat_ffpe,by.x="organ",by.y="Var1",all.x=T)

hist_ffpe <- ggplot(data=samp_ffpe2, aes(x=organ)) +
  geom_bar()+
  labs(y="Count",x=NULL,title="FFPE")+
  scale_y_continuous(breaks=seq(0, 25, by = 5),
                     labels=seq(0, 25, by = 5), limits=c(0,26),expand=c(0,0)) + 
   theme(panel.background = element_blank(),
        #panel.grid.major = element_blank(),
        panel.grid.major.y = element_line(color = "grey80",
                                          size = 0.5,
                                          linetype = 1),
        panel.border = element_rect(color="black",fill=NA),
        #text=element_text(size=15, face="bold"),
        axis.text.x = element_text(size=15,face="bold",angle=30,hjust=1),
        axis.text.y = element_text(size=15, face="bold"),
        axis.title=element_text(size=15,face="bold"),
        legend.position="none",
        legend.title=element_blank(),
        plot.title = element_text(hjust = 0.5,size=15,face="bold"))

hist_ffpe

```


