---
title: "Titration_DMRvs.UXM"
author: "Jingru Yu"
date: '2023-12-04'
output: html_document

#Update: '2023-07-02'
---

```{r load packages}
#rm(list=ls())

library(dplyr)
library(magrittr)
library(readr)
library(stringr) #str_split
library(tidyverse) #reduce
library(reshape2)
library(openxlsx)
library(data.table) #detDT
library(scales)
library("writexl") 

library(impute) #impute.knn
library(Hmisc) #describe
#install.packages("rstatix")
library(rstatix) #comparison

library(ggplot2)
library(ggbreak) #scale_y_break
library(cowplot) #ggdraw, a simple add-on to ggplot
library(ggrepel) #geom_text_repel
library(ggforce) # for 'geom_arc_bar'
library(ggrepel)
library(ggpubr) #ggarrange
library(ggbeeswarm)

### function, get descriptives from lists "describe"
descrip <- function(samp_descrip){
despm <- data.frame()
for(i in 1:length(TF_ex)){
desp1 <- as.data.frame(describe(samp_descrip[,TF_ex[i]])[["counts"]])
colnames(desp1) <- TF_ex[i]
desp2 <- as.data.frame(describe(samp_descrip[,TF_ex[i]])[["extremes"]])
colnames(desp2) <- TF_ex[i]
desp3 <- rbind(desp1, desp2)

despm <- as.data.frame(cbind.fill(despm,desp3))
}

# check distribution of medians
desp_median <- as.data.frame(describe(as.numeric(despm[".50",]))[["counts"]])
colnames(desp_median) <- "desp_median"
desp_median2 <- as.data.frame(describe(as.numeric(despm[".50",]))[["extremes"]])
if(nrow(desp_median2)>0){colnames(desp_median2) <- "desp_median"}

desp_median3 <- rbind(desp_median, desp_median2)

despm1 <- as.data.frame(cbind.fill(despm,desp_median3))
return(despm1)
}

# Squared Error is calculated as SE = (prediction - actual)^2. 
# MSE is then mean(squared errors).
# RMSE = √[ Σ(Pi – Oi)2 / n ]
# function
RMSE2 <- function(preds, actuals, na.rm = TRUE){
  res <- sqrt(mean((preds-actuals)^2, na.rm = na.rm))
  return(res)
}

GetRMSE <- function(data_se,ct_se, method_se, decimaln){
se1 <- data_se %>% filter(grp==ct_se, method==method_se)
rmse_res = RMSE2(preds=se1$Predicted/100, actuals=se1$Actual/100)
rmse_res = round(unique(rmse_res),decimaln)
print(rmse_res)
return(rmse_res)
}

pathpro <-"D:/Jingru/deconv/Data/Upload_processed" 

```


# UXM vs.CelFiE of immune titrations

```{r UXMvs.CelFiE}
#load processed results
immune_m <- read.xlsx(file.path(pathpro,"deconv",
                          "ImmuneTitrations-deconv_UXMvsCelFiE_clean.xlsx"),
                      sheet=1, skipEmptyRows=FALSE, colNames = TRUE)


se1 <- immune_m[immune_m$method=="CpG-level",] %>% filter(celltype=="Bcell")
rmse1 = mltools::mse(preds=se1$Predicted/100, actuals=se1$Actual/100)
dmr_rmse1=round(rmse1,3)
print(dmr_rmse1) #0.002
se2 <- immune_m[immune_m$method=="CpG-level",] %>% filter(celltype=="Granulocyte")
rmse2 = mltools::mse(preds=se2$Predicted/100, actuals=se2$Actual/100)
dmr_rmse2=round(rmse2,3)
print(dmr_rmse2) #0.008, 0.009 remove 100%
se3 <- immune_m[immune_m$method=="CpG-level",] %>% filter(celltype=="MonoMacrophage")
rmse3 = mltools::mse(preds=se3$Predicted/100, actuals=se3$Actual/100)
dmr_rmse3=round(rmse3,3)
print(dmr_rmse3) #0.003
se4 <- immune_m[immune_m$method=="CpG-level",] %>% filter(celltype=="Tcell")
rmse4 = mltools::mse(preds=se4$Predicted/100, actuals=se4$Actual/100)
dmr_rmse4=round(rmse4,3)
print(dmr_rmse4) #0.004

se1 <- immune_m[immune_m$method=="Fragment-level",] %>% 
  filter(celltype=="Bcell")
rmse1 = RMSE2(preds=se1$Predicted/100, actuals=se1$Actual/100)
uxm_rmse1 <- round(rmse1,3)
print(uxm_rmse1) #0.039
se2 <- immune_m[immune_m$method=="Fragment-level",] %>% 
  filter(celltype=="Granulocyte")
rmse2 = RMSE2(preds=se2$Predicted/100, actuals=se2$Actual/100)
uxm_rmse2 <- round(rmse2,3)
print(uxm_rmse2) #0.053
se3 <- immune_m[immune_m$method=="Fragment-level",] %>% 
  filter(celltype=="MonoMacrophage")
rmse3 = RMSE2(preds=se3$Predicted/100, actuals=se3$Actual/100)
uxm_rmse3 <- round(rmse3,3)
print(uxm_rmse3) #0.023
se4 <- immune_m[immune_m$method=="Fragment-level",] %>% 
  filter(celltype=="Tcell")
rmse4 = RMSE2(preds=se4$Predicted/100, actuals=se4$Actual/100)
uxm_rmse4 <- round(rmse4,3)
print(uxm_rmse4) #0.057


#plot
p.line5 <- ggplot(data=immune_m,
                  aes(x=Actual, y=Predicted, color=method.f)) + 
  geom_point(size =1.35) + 
    geom_line(size = 0.9) +
  scale_color_manual(values=c("#0042F9","red"))+
  scale_x_log10(breaks = c(0.1,0.3,1,3,10,33,100), 
                labels = c("0","0.3","1","3","10","33","100"), limits = c(0.08,105)) +
  scale_y_log10(breaks = c(0.1,0.3,1,3,10,33,100), 
                labels = c("0","0.3","1","3","10","33","100"), limits = c(0.08,105)) +
  facet_wrap( ~ celltype.f, ncol=4)+
  labs(y="Predicted (log10, %)",x="Actual (log10, %)", color="Method") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(color="black",fill=NA),
        legend.position="bottom",
        axis.text.x = element_text(size=13, face = "bold"),
        axis.text.y = element_text(size=13, face = "bold"),
        strip.text.x = element_text(size = 13, face = "bold"),
        text=element_text(size=13, face = "bold")
        )

p.line6 <- p.line5 + 
  geom_abline(intercept=0, slope = 1, color="gray", linetype="dashed", size=0.6)
p.line6

# dev.new()
# pdf(file=file.path(pathsampout,"Output_titration",
#     paste0(str_sub(Sys.Date(), start = 3),
#            "-deconv_immune.target.log_UXMvsDMR.pdf")),
#     width = 8, height = 3.1, useDingbats = FALSE)
# p.line6
# dev.off()



```

# Linechart

```{r cancercells_linechart}

m1 <- read.xlsx(file.path(pathpro,"deconv",
                          "COAD.BRCA.GBM-deconv.UXM_2scenarios_clean.xlsx"),
                sheet=1, skipEmptyRows=FALSE, colNames = TRUE)

table(m1$grp)
m1_target <- m1 %>% filter(grp %in% c("Breast-Luminal-Ep","Colon-Ep","Brain"))

m1_target <- m1_target %>%
  mutate(
    grp.f=factor(as.factor(grp), order=T,
                      levels=c("Breast-Luminal-Ep","Colon-Ep","Brain"),
                      labels=c("Breast-Luminal-Ep","Colon-Ep","Brain")),
    method.f=factor(as.factor(method), order=T,
                      levels=c("7 references","20 references"),
                      labels=c("Immune+Endothel+Actual.origin",
                               "Immune+Endothel+Potential.origin")))

rmse_brca2 <-GetRMSE(data_se=m1_target,ct_se="Breast-Luminal-Ep", 
                    method_se="7 references", decimaln=3)
rmse_brca3 <-GetRMSE(data_se=m1_target,ct_se="Breast-Luminal-Ep", 
                    method_se="20 references", decimaln=3)
rmse_coad2 <-GetRMSE(data_se=m1_target,ct_se="Colon-Ep", 
                    method_se="7 references", decimaln=3)
rmse_coad3 <-GetRMSE(data_se=m1_target,ct_se="Colon-Ep", 
                    method_se="20 references", decimaln=3)
rmse_gbm2 <-GetRMSE(data_se=m1_target,ct_se="Brain", 
                    method_se="7 references", decimaln=3)
rmse_gbm3 <-GetRMSE(data_se=m1_target,ct_se="Brain", 
                    method_se="20 references", decimaln=3)

#draw line chart
p.line9 <- ggplot(data=m1_target,
                  aes(x=Actual, y=Predicted, color=method.f)) + 
   geom_abline(intercept=0, slope = 1, color="gray", linetype="dashed", size=0.6) +
  geom_point(size =1.35) + 
  geom_line(size = 0.9) +
  scale_color_manual(values=c("#053c5e","#a31621"))+
  #geom_smooth(method = "glm", formula = y ~x, se=F) +
  scale_x_continuous(breaks = c(0,7.5,15,30,60,100), 
                labels = c(0,7.5,15,30,60,100), limits = c(0,100)) +
  scale_y_continuous(breaks = c(0,7.5,15,30,60,100), 
                labels = c(0,7.5,15,30,60,100), limits = c(0,100)) +
  facet_wrap( ~ grp.f, ncol=3)+
  labs(y="Predicted (%)",x="Actual (%)", color="Method") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(color="black",fill=NA),
        legend.position="bottom",
        axis.text.x = element_text(size=13, face = "bold", 
                                   angle=45,hjust=1),
        axis.text.y = element_text(size=13, face = "bold"),
        strip.text.x = element_text(size = 13,  face = "bold"),
        text=element_text(size=13)) + 
  guides(fill = guide_legend(ncol = 1))
p.line9

# dev.new()  
# pdf(file=file.path(pathsampout,"Output_titration",
#     paste0(str_sub(Sys.Date(), start = 3),"-deconv_3cancers.uxm_linechart.pdf")), 
#     width = 6.2, height = 3.2, useDingbats = FALSE)
# p.line9
# dev.off()

```


# In silico XR data of CelFie and UXM

```{r plots}

WGBSsamples <- read.xlsx(file.path(pathpro, "deconv",
          "WGBSsampleMix_UXMvsCelFiE.xlsx"),
           sheet=1, skipEmptyRows=FALSE, colNames = TRUE)
table(WGBSsamples$origin) #Colon   CSF Liver  Lung 

#remove the fourth sample, target cell proportion=3%
WGBSsamples <- WGBSsamples[!(WGBSsamples$samp_id2==4 & WGBSsamples$method.f=="Fragment-level"),]

#merge 4 data 
samp_m2_colon1 <- WGBSsamples[WGBSsamples$origin=="Colon",] %>% filter(celltype=="EpiColon")
samp_m2_colon1$target <- "EpiColon"
samp_m2_brain1 <- WGBSsamples[WGBSsamples$origin=="CSF",] %>% filter(celltype=="Neuron")
samp_m2_brain1$target <- "Neuron"
samp_m2_liver1 <- WGBSsamples[WGBSsamples$origin=="Liver",] %>% filter(celltype=="Hepatocyte")
samp_m2_liver1$target <- "Hepatocyte"
samp_m2_lung6ct1 <- WGBSsamples[WGBSsamples$origin=="Lung",] %>% filter(celltype=="EpiLungAlveolar")
samp_m2_lung6ct1$target <- "EpiLungAlveolar"


samp_m3 <- rbind(samp_m2_colon1,samp_m2_brain1,samp_m2_liver1,samp_m2_lung6ct1)

samp_m3 <- samp_m3 %>% 
  mutate(grp=celltype,
         grp.f=factor(as.factor(grp),order=T,
                      levels=c("Neuron","EpiLungAlveolar","Hepatocyte","EpiColon"),
                      labels=c("Neuron","Lung alveolar epi.","Hepatocyte","Colon epi.")))

colon_dmr <- 
  GetRMSE(data_se=samp_m3,ct_se="EpiColon", method_se="CpG-level", decimaln=3)
neuron_dmr <- 
  GetRMSE(data_se=samp_m3,ct_se="Neuron", method_se="CpG-level", decimaln=3)
lung_dmr <- 
  GetRMSE(data_se=samp_m3,ct_se="EpiLungAlveolar", method_se="CpG-level", decimaln=3)
liver_dmr <- 
  GetRMSE(data_se=samp_m3,ct_se="Hepatocyte", method_se="CpG-level", decimaln=3)

colon_uxm <- 
  GetRMSE(data_se=samp_m3,ct_se="EpiColon", method_se="Fragment-level", decimaln=3)
neuron_uxm <- 
  GetRMSE(data_se=samp_m3,ct_se="Neuron", method_se="Fragment-level", decimaln=3)
lung_uxm <- 
  GetRMSE(data_se=samp_m3,ct_se="EpiLungAlveolar", method_se="Fragment-level", decimaln=3)
liver_uxm <- 
GetRMSE(data_se=samp_m3,ct_se="Hepatocyte", method_se="Fragment-level", decimaln=3)

table(samp_m3$grp.f)
# only top30
se.dot5 <- ggplot(data=samp_m3, 
                  aes(x=Actual, y=Predicted, color=method.f)) + 
  geom_abline(intercept=0, slope = 1, color="gray", linetype="dashed", size=0.6) +
  geom_point(size =1.35) + 
  geom_line(size = 0.9) +
  geom_errorbar(aes(ymin=ymin, ymax=Predicted+sd),width=.15, size=0.7) +
  scale_color_manual(values=c("#0042F9","red"))+
  #geom_smooth(method = "glm", formula = y ~x, se=F) +
  scale_x_log10(breaks = c(0.1,0.33,1,3,10,30,100), 
                labels = c("0","0.3","1","3","10","33","100"), limits = c(0.07,105)) +
  scale_y_log10(breaks = c(0.1,0.33,1,3,10,33,100), 
                labels = c("0","0.3","1","3","10","33","100"), limits = c(0.07,105)) +
  facet_wrap( ~ grp.f, ncol=4)+
  labs(y="Predicted (log10, %)",x="Actual (log10, %)", color="Method") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(color="black",fill=NA),
        legend.position="bottom",
        axis.text.x = element_text(size=13, face = "bold"),
        axis.text.y = element_text(size=13, face = "bold"),
        strip.text.x = element_text(size = 13,  face = "bold"),
        text=element_text(size=13)
        )

dat_text <- data.frame(
  label = c(paste0("RMSE (CpG)=",neuron_dmr,"\n", "RMSE (frag.)=",neuron_uxm),
            paste0("RMSE (CpG)=",lung_dmr,"\n", "RMSE (frag.)=",lung_uxm),
            paste0("RMSE (CpG)=",liver_dmr,"\n", "RMSE (frag.)=",liver_uxm),
            paste0("RMSE (CpG)=",colon_dmr,"\n", "RMSE (frag.)=",colon_uxm)),
  grp  = c(1,2,3,4))

dat_text$grp.f <- 
  factor(as.factor(dat_text$grp), order=T,levels=c(1,2,3,4),
         labels=c("Neuron","Lung alveolar epi.","Hepatocyte","Colon epi."))


se.dot6 <- se.dot5 + 
  geom_abline(intercept=0, slope = 1, color="gray", linetype="dashed", size=0.6) +
  geom_text(data = dat_text, label=dat_text$label,
            x=0.001, y = Inf,hjust=0.5,vjust=1.4,
            inherit.aes = F,size=3) 

se.dot6   


```

# plasma

```{r plasmas}

#output_test_uxm
pnorm <- read.csv(file=file.path(pathpro, "deconv",
                                "output_3plasma_9ref_240208.csv"),
                   header = TRUE, sep = ",")

pnorm$pcomb.wgbs_mean <- round(rowMeans(pnorm[,c(3,5,7)])*100, 1)
pnorm$pcomb.inXR_mean <- round(rowMeans(pnorm[,c(4,6,8)])*100, 1)

pnorm1 <- pnorm[,c(1,2,9,10)] %>%
  mutate(P2_perc=round(P2dil_comb3cpg.hg38_PE.dedup_sorted*100,1))

pnorm4 <- pnorm1[,-2]

lc1 <- pnorm4[c(1,2,5),]
lc2 <- as.data.frame(t(as.data.frame(colSums(lc1[,-1]))))
lc2$CellType ="Lymphocytes"
pnorm4_lc <- rbind(pnorm4[-c(1,2,5),],lc2)

pnorm4_lc$WGBS_Loyfer=c(29.7,20,5.5,5.5,31.4,3.1,2.5)

#wide to long data
se.long <- melt(setDT(as.data.frame(pnorm4_lc)),id.vars = 1, 
                 measure.vars = 2:length(colnames(pnorm4_lc)), variable.name = "Sample_id")


se.long_plot <- se.long %>%
  mutate(
         samp.f = factor(as.factor(Sample_id), order=T,
                levels=c("P2_perc","pcomb.inXR_mean","pcomb.wgbs_mean","WGBS_Loyfer"),
                labels=c("FLEXseq of Donor P2","CCGGflanks of WGBS2","WGBS2","WGBS1")),
          ct.f=factor(as.factor(CellType),
                       levels=c("Blood-Granul","Blood-Mono+Macro",
                                "Endothel","Eryth-prog","Liver-Hep",
                                "Lymphocytes","Megakaryocytes"),
                       labels=c("Granulocyte","MonoMacrophage",
                                "Endothelium","Erythroid\nprogenitor",
                                "Hepatocyte","Lymphocytes","Megakaryocytes")))

se.long_plot <- se.long_plot[order(se.long_plot$Sample_id,se.long_plot$ct.f),]

se.long_plot2 <- se.long_plot %>%
  group_by(Sample_id) %>%
  mutate(x_end = cumsum(value),
         x_start=value) %>% 
  arrange(samp.f)

#ref from "18WGBSliverBenign_subtraction_deconv"
width=0.4
p.bar1 <- ggplot(se.long_plot2, aes(value, y=samp.f)) +
  geom_bar(aes(fill = forcats::fct_rev(ct.f)), 
           stat = "identity", position="fill",width=width) +
  scale_fill_manual(values=rev(c("#fac748","#053c5e","#a31621","#F8766D",
                                 "#00BFC4","#B17DEF","#0042F9"))) + 
  labs(x="Predicted",y="Sample",fill="ct.f") +
    scale_x_continuous(position = "top",
                     expand = expansion(mult=c(0,0)),
                     breaks = seq(0,1,by=0.2), labels=c(0,0.2,0.4,0.6,0.8,1)) +
   theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(color="black",fill=NA),
        axis.title.x = element_text(face="bold", size = 13),
        axis.title.y = element_text(face="bold", size = 13),
        legend.title = element_text(face="bold", size = 10),
        axis.text.x = element_text(size=13, face="bold"),
        axis.text.y = element_text(size=13, face="bold"),
        legend.position = "right") +
  guides(fill=guide_legend(title="Cell types"))
p.bar1

# dev.new()
# pdf(file=file.path(pathsampout,
#                    paste0(str_sub(Sys.Date(), start = 3),
#                    "-deconv_plasma4_stacked_uxm.pdf")),
#     width = 8, height = 4, useDingbats = FALSE)
# p.bar1
# dev.off()


```


